{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-2/4.4.0/mirrg.kotlin.helium-kotlin-2-2-4.4.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-2",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.4.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.4.0.jar",
          "size": 19116,
          "sha512": "2fb5155110e8720ab1a32ec2beb8dabffda75d42a08dd6deb36f9d24cd4f952587c1b2f131dad1117a2aeb90c30225cae8ccd2b0a6663eba0712caf39fad731f",
          "sha256": "ae87be13f0dac668ddd2b00ac002fc219f4a8ea9afed9a020c62ad69e27ea4d0",
          "sha1": "cd3b291843335ad160aecf58aa1fca27763ea01a",
          "md5": "dc837de74e69b80db46fff3d45d05e34"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.4.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.4.0.jar",
          "size": 19116,
          "sha512": "2fb5155110e8720ab1a32ec2beb8dabffda75d42a08dd6deb36f9d24cd4f952587c1b2f131dad1117a2aeb90c30225cae8ccd2b0a6663eba0712caf39fad731f",
          "sha256": "ae87be13f0dac668ddd2b00ac002fc219f4a8ea9afed9a020c62ad69e27ea4d0",
          "sha1": "cd3b291843335ad160aecf58aa1fca27763ea01a",
          "md5": "dc837de74e69b80db46fff3d45d05e34"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.4.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.4.0-sources.jar",
          "size": 4028,
          "sha512": "5ef4b0c357557f9dbd9b211aeb51bc8ee7c816125ccb0f977761f621ea10c6e0f9b11a37ed28036a916f582c550f8136405c1c51d6eeadc15f367df9398b8dfd",
          "sha256": "dfe319ee38219a70fd6a327c62442fa5c9f7300902beacfcd24ac86783d7ee8a",
          "sha1": "4c1e2fcd3897c74d99fbe3411ba98bf3744d189a",
          "md5": "f9cf3bbfc427f9ab74b6359e49c7133d"
        }
      ]
    }
  ]
}
