{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-9/4.2.0/mirrg.kotlin.helium-kotlin-1-9-4.2.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-9",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-9-mingwx64-4.2.0.klib",
          "size": 24925,
          "sha512": "c5a514a15b7bb1a9874ae55360ef5317c1e4fd01adb890d9b44f3b67b4bbd947a05f377b1f52c6e98382b73e8d0359e1eb1f1d54683d6531bceb4a68ebac6b3e",
          "sha256": "680cd2562803fd691a657ec293cb508959d9e37afcca8fc26ed26621d9508b8c",
          "sha1": "f3ce0feaa085ffc9756abb02e0e011ec81b384c9",
          "md5": "02f1d483b80712aeca3b9c384bdc03e8"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-mingwx64-4.2.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-mingwx64-4.2.0-sources.jar",
          "size": 3668,
          "sha512": "88e69b0a944fe896966342f4108ed2effa9da1b5deab08ba414424fcd1cd64e81a5ac3ef5b509c8a451141dbba19abefcaa8256205b62336fb6c341b42573ea2",
          "sha256": "2e82a2c8712db07e240ef87e1102ac3eaf7d9091d72119be618ec1204fbc8d90",
          "sha1": "a85c6845aed7e8355126fedebfd007e6a91dafca",
          "md5": "4893911cd7d818cc631dbbd20993c8e4"
        }
      ]
    }
  ]
}
