{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium/1.1.0/mirrg.kotlin.helium-1.1.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium.klib",
          "url": "mirrg.kotlin.helium-linuxx64-1.1.0.klib",
          "size": 23965,
          "sha512": "440f3dae28b7964717a3dfe378d45e308354c75c83472126a9946f348393bbcec015da99be0699c54c7c3b165074c3882ad33c82fed65447966c55c66e1e2c9c",
          "sha256": "978695c4475e0f061b4e4735d9914a6d44daa5e0ebd6be15d2ac5fcd53f5efd2",
          "sha1": "fb716fb01b572a59592531a5d3c6363d34d6306f",
          "md5": "0f34a1a259033cda3d7f19f256476e82"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-linuxx64-1.1.0-sources.jar",
          "url": "mirrg.kotlin.helium-linuxx64-1.1.0-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    }
  ]
}
