{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-0/4.2.0/mirrg.kotlin.helium-kotlin-2-0-4.2.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-0",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-0-linuxx64-4.2.0.klib",
          "size": 23859,
          "sha512": "7af9308dca0284bc5b9e390973437a938498e14e7e3e98ac4e6f8c9f6a0661b983540bb661b6f3bfd7446a2c5d2b758515596824a916708a7a7dd7f63dba7b9c",
          "sha256": "becc4c7021fd4ed9a0ade6031d9ec8a2b85e8fc1885bc46afe87f6b326a7cff6",
          "sha1": "b7881efe76532d28471deee47617d44b64f83e33",
          "md5": "1463c6a08f435280461d620f8f8b09c6"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-linuxx64-4.2.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-linuxx64-4.2.0-sources.jar",
          "size": 3668,
          "sha512": "88e69b0a944fe896966342f4108ed2effa9da1b5deab08ba414424fcd1cd64e81a5ac3ef5b509c8a451141dbba19abefcaa8256205b62336fb6c341b42573ea2",
          "sha256": "2e82a2c8712db07e240ef87e1102ac3eaf7d9091d72119be618ec1204fbc8d90",
          "sha1": "a85c6845aed7e8355126fedebfd007e6a91dafca",
          "md5": "4893911cd7d818cc631dbbd20993c8e4"
        }
      ]
    }
  ]
}
