{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-6/4.0.1/mirrg.kotlin.helium-kotlin-1-6-4.0.1.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-6",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.6"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-6.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-6-linuxx64-4.0.1.klib",
          "size": 22137,
          "sha512": "b425a4da73dcfe6da80bbe3e2d8e754154d04ea4f8dab314783066b6b2bf7fd2bc5de2e6adeebedfe5b1246cad95993786b0d711bf4be503395c5e5878552948",
          "sha256": "21cdf42c41d2bcbb797580c9808b047342ee1dabf82731ca959896dff56263c0",
          "sha1": "af1091ba6b5bcd4de115952234188a25e9c8798a",
          "md5": "c8e630220ed619f99eb20a033e713af7"
        }
      ]
    }
  ]
}
