{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-2/4.4.0/mirrg.kotlin.helium-kotlin-2-2-4.4.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-2",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-linuxX64Main-4.4.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-2-linuxx64-4.4.0.klib",
          "size": 26030,
          "sha512": "76d64381e9074a9c97a6ef4c1619176f0d1ea847034409adc5bf56f2cf08dabc0f9a01870806d4a3224eb88abecf88c903dcec4520bc4a1b471f7a1341a8d351",
          "sha256": "34c2710721f8ccbdafb7c15870a0b67747586d20e6581cf373a77924ca80db93",
          "sha1": "530b34e74dcc6668ec16031a88b085654f9ec1d3",
          "md5": "e89bd79a89547858b7478a2bfb9d322f"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-linuxx64-4.4.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-linuxx64-4.4.0-sources.jar",
          "size": 4028,
          "sha512": "5ef4b0c357557f9dbd9b211aeb51bc8ee7c816125ccb0f977761f621ea10c6e0f9b11a37ed28036a916f582c550f8136405c1c51d6eeadc15f367df9398b8dfd",
          "sha256": "dfe319ee38219a70fd6a327c62442fa5c9f7300902beacfcd24ac86783d7ee8a",
          "sha1": "4c1e2fcd3897c74d99fbe3411ba98bf3744d189a",
          "md5": "f9cf3bbfc427f9ab74b6359e49c7133d"
        }
      ]
    }
  ]
}
