{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-9/4.1.0/mirrg.kotlin.helium-kotlin-1-9-4.1.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-9",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-js-4.1.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-9-js-4.1.0.klib",
          "size": 27103,
          "sha512": "8709f713626bf6c8a9c9aeda9e62e3bd43c6ad08100c8819a6f0dfab5fb395520e4b56e2b33a1ced205c741b6119c4e884e192903e05b16bc483e3d18cce4a46",
          "sha256": "0a3ffbf8afe771267bc50519008cba8cbc69998bf946cb267dc9524bdb9d15e7",
          "sha1": "a701f5e5572fd98d57c6fc539fe2425d2690cce5",
          "md5": "9ab3bb42eff460d3de9cfc7532e82fc7"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-js-4.1.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-9-js-4.1.0.klib",
          "size": 27103,
          "sha512": "8709f713626bf6c8a9c9aeda9e62e3bd43c6ad08100c8819a6f0dfab5fb395520e4b56e2b33a1ced205c741b6119c4e884e192903e05b16bc483e3d18cce4a46",
          "sha256": "0a3ffbf8afe771267bc50519008cba8cbc69998bf946cb267dc9524bdb9d15e7",
          "sha1": "a701f5e5572fd98d57c6fc539fe2425d2690cce5",
          "md5": "9ab3bb42eff460d3de9cfc7532e82fc7"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-js-4.1.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-js-4.1.0-sources.jar",
          "size": 3626,
          "sha512": "9d61d877e6915037ec99a454bd9a03217b94c677f0954c98105c711a6ad9855c1ef41303f332b14dc22af30e0f5a839630dbf2b6b386f66aab5c4913ae24fafd",
          "sha256": "2071b17f6d792fafadbad4b4f751ed40c13ebd37f6834a7a94308746cba7b453",
          "sha1": "7d434e1d3ec8b0e1838321bc7954628c5d6f0677",
          "md5": "186ba7c2ee70500e0e848017ec51b678"
        }
      ]
    }
  ]
}
