{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-6/4.3.0/mirrg.kotlin.helium-kotlin-1-6-4.3.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-6",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-6-jvm-4.3.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-6-jvm-4.3.0.jar",
          "size": 20961,
          "sha512": "db2c3e4c268fda0b658cf6990d78590a0b46dbf7b9ea5674d022a37d7a7b7bc8fa26edde852921e629a9feb9ff852fe0a5eaf3738ad03af75adb1f1259497315",
          "sha256": "eff8a8f41e52ab61523ea8e7bb7748a7bc661c8c515578fdf95f80c3899de467",
          "sha1": "ba409e7958e5d0985c7d260b97320651571527cb",
          "md5": "4509922a080729522b4bbb1b6978b560"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-6-jvm-4.3.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-6-jvm-4.3.0.jar",
          "size": 20961,
          "sha512": "db2c3e4c268fda0b658cf6990d78590a0b46dbf7b9ea5674d022a37d7a7b7bc8fa26edde852921e629a9feb9ff852fe0a5eaf3738ad03af75adb1f1259497315",
          "sha256": "eff8a8f41e52ab61523ea8e7bb7748a7bc661c8c515578fdf95f80c3899de467",
          "sha1": "ba409e7958e5d0985c7d260b97320651571527cb",
          "md5": "4509922a080729522b4bbb1b6978b560"
        }
      ]
    }
  ]
}
