{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-9/4.0.1/mirrg.kotlin.helium-kotlin-1-9-4.0.1.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-9",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-js-4.0.1.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-9-js-4.0.1.klib",
          "size": 26559,
          "sha512": "221032cc18fa270c28399cd48833c39c5712b221236837066a91ff9cc2a75620b674d3f65fca1df07bdbd5ef58e3fc5001e28a9c247bf7e6565c4120d5914878",
          "sha256": "21eb7aab26fc79ca693b248b9f0ae9a4a23486fa0eb222b1dfe963c9bc788700",
          "sha1": "4282dcf54c97baf23369e9e4178ab1ea9903ae52",
          "md5": "9726da8dbcff6a26fe274052c8468596"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-js-4.0.1.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-9-js-4.0.1.klib",
          "size": 26559,
          "sha512": "221032cc18fa270c28399cd48833c39c5712b221236837066a91ff9cc2a75620b674d3f65fca1df07bdbd5ef58e3fc5001e28a9c247bf7e6565c4120d5914878",
          "sha256": "21eb7aab26fc79ca693b248b9f0ae9a4a23486fa0eb222b1dfe963c9bc788700",
          "sha1": "4282dcf54c97baf23369e9e4178ab1ea9903ae52",
          "md5": "9726da8dbcff6a26fe274052c8468596"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-js-4.0.1-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-js-4.0.1-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    }
  ]
}
