{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium/1.0.0/mirrg.kotlin.helium-1.0.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium.klib",
          "url": "mirrg.kotlin.helium-linuxarm64-1.0.0.klib",
          "size": 23835,
          "sha512": "e4c4b319cbb388048c6f750a4feef0befb471024fdd76cca68d35dc9b3e9f5fe655db413761e745a0f4abf63cc72b6e356dd2158a4caaac5ade2f22adc3497ae",
          "sha256": "21895d92841c4c62ed0bff5b02196a901dd125a89ae4462381c0cc29c651236b",
          "sha1": "20a337573fad7a4343a5c1de583a1508eedfbe99",
          "md5": "932ffa23c7e992d9b9de7456ac45e288"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-linuxarm64-1.0.0-sources.jar",
          "url": "mirrg.kotlin.helium-linuxarm64-1.0.0-sources.jar",
          "size": 3516,
          "sha512": "16f328c14e4c8d51e306d7be326a5bba000edf7be1c816c6a5040da8529c6f84cfd094e377e1e3b359ceab1c258255041cce09b6089e22ae1b6d7753da6784ea",
          "sha256": "0e1a7c77d0cb1563166c7482ffea926d9edaaafe43e32e9c4f13316ffddb1df1",
          "sha1": "5bf059bff47c27d5e2b664021017ca3fd9d71584",
          "md5": "b3a1ad12d5f11c4277f36077942dc05d"
        }
      ]
    }
  ]
}
