{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-8/4.0.1/mirrg.kotlin.helium-kotlin-1-8-4.0.1.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-8",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8-js-4.0.1.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-8-js-4.0.1.klib",
          "size": 24724,
          "sha512": "fa465f94ea2514ffb925dd7ce9d05a69c24ccd671a89aab1c3757aa5faca240824b6dc03484b820de20dd4ff2b7123a89c29a21a68f08cbdaff81c7de0201d68",
          "sha256": "7c5d6fe1ed14f7f7859e1226ef3e7d928c9fdb970fc4817cf49c289d4fc055f6",
          "sha1": "31aea739914a45337367fb0a4e605f3c5b61232f",
          "md5": "29aa945563ff1f78fc54e216100c89fe"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8-js-4.0.1.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-8-js-4.0.1.klib",
          "size": 24724,
          "sha512": "fa465f94ea2514ffb925dd7ce9d05a69c24ccd671a89aab1c3757aa5faca240824b6dc03484b820de20dd4ff2b7123a89c29a21a68f08cbdaff81c7de0201d68",
          "sha256": "7c5d6fe1ed14f7f7859e1226ef3e7d928c9fdb970fc4817cf49c289d4fc055f6",
          "sha1": "31aea739914a45337367fb0a4e605f3c5b61232f",
          "md5": "29aa945563ff1f78fc54e216100c89fe"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8-js-4.0.1-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-8-js-4.0.1-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    }
  ]
}
