{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-7/4.3.0/mirrg.kotlin.helium-kotlin-1-7-4.3.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-7",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-7.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-7-linuxarm64-4.3.0.klib",
          "size": 24255,
          "sha512": "d9f7dbd8a7d9834563441abbf032673a71ef205c4b8aa85042a29c7ce027f2c083f1594029f9e36dc49fe88d0c714876a1a6c489dabea64f41dab9897e651aed",
          "sha256": "9604cf6e9a3e7029d9b869996146616e3ff44a80d0e84deeaa5f3a0b940ceae7",
          "sha1": "f35e784798a494b0d3881c0a2861bd100c2358f1",
          "md5": "c97fec6f78f906b54e0c356631078c46"
        }
      ]
    }
  ]
}
