{
  "formatVersion": "1.1",
  "component": {
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-6",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-6-metadata-4.1.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-6-4.1.0.jar",
          "size": 9033,
          "sha512": "f021a93230917c9aa94afa5bd3f9dd2f3d67c7cf7b35da70881539419c4625b03f33423a8383b64742eacc34f23faf62e1b57d6173452f8e81b707d7d9983bf8",
          "sha256": "311e0c5900bafa58b267dc48d9a523713a122d9ec19417dc60a7601a73599ae3",
          "sha1": "790b69b50ef1e1c48614d277dc636b2db79b7d3e",
          "md5": "cd6edaf09f2095125cfc21d3fc4b2180"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-1-6-js/4.1.0/mirrg.kotlin.helium-kotlin-1-6-js-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-1-6-js",
        "version": "4.1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-1-6-js/4.1.0/mirrg.kotlin.helium-kotlin-1-6-js-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-1-6-js",
        "version": "4.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-1-6-jvm/4.1.0/mirrg.kotlin.helium-kotlin-1-6-jvm-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-1-6-jvm",
        "version": "4.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-1-6-jvm/4.1.0/mirrg.kotlin.helium-kotlin-1-6-jvm-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-1-6-jvm",
        "version": "4.1.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-1-6-linuxarm64/4.1.0/mirrg.kotlin.helium-kotlin-1-6-linuxarm64-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-1-6-linuxarm64",
        "version": "4.1.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-1-6-linuxx64/4.1.0/mirrg.kotlin.helium-kotlin-1-6-linuxx64-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-1-6-linuxx64",
        "version": "4.1.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-1-6-mingwx64/4.1.0/mirrg.kotlin.helium-kotlin-1-6-mingwx64-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-1-6-mingwx64",
        "version": "4.1.0"
      }
    }
  ]
}
