{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-1/4.1.0/mirrg.kotlin.helium-kotlin-2-1-4.1.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-1",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-js-4.1.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-1-js-4.1.0.klib",
          "size": 26459,
          "sha512": "5101ea44bd1965089abf6888fd813eda9718149f256ce308d0f2bfdd9a0ca04f3ceee064b6825c67ea35a537d14413d47f307db679e1c4026bc4567dc9983db5",
          "sha256": "05fd382204a7c3e9b595db0a2128c19e738f9df0d16a59c361bba923ffc1ac2e",
          "sha1": "d7757c87629e9c6350293f6ac1dedc1c73cb619f",
          "md5": "0c9142ab0ac12f49f0c6947fc3ab1fff"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-js-4.1.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-1-js-4.1.0.klib",
          "size": 26459,
          "sha512": "5101ea44bd1965089abf6888fd813eda9718149f256ce308d0f2bfdd9a0ca04f3ceee064b6825c67ea35a537d14413d47f307db679e1c4026bc4567dc9983db5",
          "sha256": "05fd382204a7c3e9b595db0a2128c19e738f9df0d16a59c361bba923ffc1ac2e",
          "sha1": "d7757c87629e9c6350293f6ac1dedc1c73cb619f",
          "md5": "0c9142ab0ac12f49f0c6947fc3ab1fff"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-js-4.1.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-js-4.1.0-sources.jar",
          "size": 3626,
          "sha512": "9d61d877e6915037ec99a454bd9a03217b94c677f0954c98105c711a6ad9855c1ef41303f332b14dc22af30e0f5a839630dbf2b6b386f66aab5c4913ae24fafd",
          "sha256": "2071b17f6d792fafadbad4b4f751ed40c13ebd37f6834a7a94308746cba7b453",
          "sha1": "7d434e1d3ec8b0e1838321bc7954628c5d6f0677",
          "md5": "186ba7c2ee70500e0e848017ec51b678"
        }
      ]
    }
  ]
}
