{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-9/4.1.0/mirrg.kotlin.helium-kotlin-1-9-4.1.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-9",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-9-linuxarm64-4.1.0.klib",
          "size": 24545,
          "sha512": "b2f2cbc8eda2e4f817386d32a883f1b5900aeb6e50965280fe696a2d2824a3f21b8d68419c64677fd0cb6c272b040e82635f207cb28a39521f0e5cf48b211c8e",
          "sha256": "d6e08283b637efec9a2496809c9bd75cd9f46c21b82f3e4dbe605caf24d9611f",
          "sha1": "4f1173be36f2e8f941953cbe0dd0dea16a08c192",
          "md5": "a3d5b8f7120d9fe420726c5c61b14e69"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-linuxarm64-4.1.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-linuxarm64-4.1.0-sources.jar",
          "size": 3626,
          "sha512": "9d61d877e6915037ec99a454bd9a03217b94c677f0954c98105c711a6ad9855c1ef41303f332b14dc22af30e0f5a839630dbf2b6b386f66aab5c4913ae24fafd",
          "sha256": "2071b17f6d792fafadbad4b4f751ed40c13ebd37f6834a7a94308746cba7b453",
          "sha1": "7d434e1d3ec8b0e1838321bc7954628c5d6f0677",
          "md5": "186ba7c2ee70500e0e848017ec51b678"
        }
      ]
    }
  ]
}
