{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-1/4.3.0/mirrg.kotlin.helium-kotlin-2-1-4.3.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-1",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.3.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.3.0.jar",
          "size": 18823,
          "sha512": "a2c4b21414ab1aecbbf79bd70333cfcc5d3a5935df83fc1a18855e13bb958089c3949dd17c7db968dbf023c420aa511e5fad8bc260edfcab8ad1165960d83a81",
          "sha256": "6a88adb450e822662571a9c2d7d06d123e0588c7bc07cdc8a643b7f2dcb1e117",
          "sha1": "cf663d52c65f1dc9e8b5f468572cd73fc76ae281",
          "md5": "6ca843e15b2c50b43b6166eb37e62a7d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.3.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.3.0.jar",
          "size": 18823,
          "sha512": "a2c4b21414ab1aecbbf79bd70333cfcc5d3a5935df83fc1a18855e13bb958089c3949dd17c7db968dbf023c420aa511e5fad8bc260edfcab8ad1165960d83a81",
          "sha256": "6a88adb450e822662571a9c2d7d06d123e0588c7bc07cdc8a643b7f2dcb1e117",
          "sha1": "cf663d52c65f1dc9e8b5f468572cd73fc76ae281",
          "md5": "6ca843e15b2c50b43b6166eb37e62a7d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.3.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.3.0-sources.jar",
          "size": 3797,
          "sha512": "10b2749af16fe3e272cc741a193ab9d8c8b635c44c4c4ddd483ba3a737544ff39ec390e5f3d2b3e99d397e74fd7770183a49dde6c277651d9bbfdc672c95e2e5",
          "sha256": "f774c0348ba67ca581353115b1eea93207dd3c1dc88a78548caf7ce81a7780e3",
          "sha1": "c1e847f8c4faf3dfb9da97744313ee5a27cdfb21",
          "md5": "73401ad3093fe01879126c8e622408d9"
        }
      ]
    }
  ]
}
