{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-1/4.3.0/mirrg.kotlin.helium-kotlin-2-1-4.3.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-1",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-js-4.3.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-1-js-4.3.0.klib",
          "size": 28266,
          "sha512": "ad95cf97938b0926715d5e60091f2df2ab89f7932aba27febf52c97f61ed719b67ff887cd1e7a0116c7c26f92d88c6585362173d936237f3c8bde80a58bc3a46",
          "sha256": "fa34d6d21c6e8b14432f3108cbbe64daaa3262b6ee53114ddf11173cce1cba61",
          "sha1": "48bb928e8edc3b078bb6afaedf883000626901c6",
          "md5": "894d8c52c9bb0f19dc047f57531598c1"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-js-4.3.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-1-js-4.3.0.klib",
          "size": 28266,
          "sha512": "ad95cf97938b0926715d5e60091f2df2ab89f7932aba27febf52c97f61ed719b67ff887cd1e7a0116c7c26f92d88c6585362173d936237f3c8bde80a58bc3a46",
          "sha256": "fa34d6d21c6e8b14432f3108cbbe64daaa3262b6ee53114ddf11173cce1cba61",
          "sha1": "48bb928e8edc3b078bb6afaedf883000626901c6",
          "md5": "894d8c52c9bb0f19dc047f57531598c1"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-js-4.3.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-js-4.3.0-sources.jar",
          "size": 3797,
          "sha512": "10b2749af16fe3e272cc741a193ab9d8c8b635c44c4c4ddd483ba3a737544ff39ec390e5f3d2b3e99d397e74fd7770183a49dde6c277651d9bbfdc672c95e2e5",
          "sha256": "f774c0348ba67ca581353115b1eea93207dd3c1dc88a78548caf7ce81a7780e3",
          "sha1": "c1e847f8c4faf3dfb9da97744313ee5a27cdfb21",
          "md5": "73401ad3093fe01879126c8e622408d9"
        }
      ]
    }
  ]
}
