{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-1/4.0.1/mirrg.kotlin.helium-kotlin-2-1-4.0.1.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-1",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-linuxX64Main-4.0.1.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-1-linuxx64-4.0.1.klib",
          "size": 22148,
          "sha512": "f2e9917af64528045d404afc263467212c3174ccbfa0c338aef973f020fdce2a3a324593e5c44dcf202b79415c615ff0643bae2d709841ccdee9c993996a557c",
          "sha256": "de1457bd9e22ef58b5cd572283c6fc0265eeaeadd795d5e97d1f03e9633702aa",
          "sha1": "58aa6745ffa3bcc2760a4b3309dd38a54b4250a3",
          "md5": "b936cd1b032481b4742bbabe131ba8cc"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-linuxx64-4.0.1-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-linuxx64-4.0.1-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    }
  ]
}
