{
  "formatVersion": "1.1",
  "component": {
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-1",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-metadata-4.3.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-4.3.0.jar",
          "size": 8933,
          "sha512": "302af10232d3a09c4393edd760413c37f22b76c27d04ae72b542ef556747de275b25696bec4f0948ca463b5d90e7bb52c95532c733fe28d1844978b8cccbdd5f",
          "sha256": "59101559d1eb2b2f0fa06335ca3d6660448cecb5bb94350838422838ee079a38",
          "sha1": "4d36e1eaba7ab70407d1b0f1cb34307c23527fdc",
          "md5": "7da6f62f7970cd8104f099ec4a8c97a8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-kotlin-4.3.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-4.3.0-sources.jar",
          "size": 3797,
          "sha512": "10b2749af16fe3e272cc741a193ab9d8c8b635c44c4c4ddd483ba3a737544ff39ec390e5f3d2b3e99d397e74fd7770183a49dde6c277651d9bbfdc672c95e2e5",
          "sha256": "f774c0348ba67ca581353115b1eea93207dd3c1dc88a78548caf7ce81a7780e3",
          "sha1": "c1e847f8c4faf3dfb9da97744313ee5a27cdfb21",
          "md5": "73401ad3093fe01879126c8e622408d9"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-js/4.3.0/mirrg.kotlin.helium-kotlin-2-1-js-4.3.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-js",
        "version": "4.3.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-js/4.3.0/mirrg.kotlin.helium-kotlin-2-1-js-4.3.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-js",
        "version": "4.3.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-js/4.3.0/mirrg.kotlin.helium-kotlin-2-1-js-4.3.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-js",
        "version": "4.3.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-jvm/4.3.0/mirrg.kotlin.helium-kotlin-2-1-jvm-4.3.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-jvm",
        "version": "4.3.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-jvm/4.3.0/mirrg.kotlin.helium-kotlin-2-1-jvm-4.3.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-jvm",
        "version": "4.3.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-jvm/4.3.0/mirrg.kotlin.helium-kotlin-2-1-jvm-4.3.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-jvm",
        "version": "4.3.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxarm64/4.3.0/mirrg.kotlin.helium-kotlin-2-1-linuxarm64-4.3.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxarm64",
        "version": "4.3.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxarm64/4.3.0/mirrg.kotlin.helium-kotlin-2-1-linuxarm64-4.3.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxarm64",
        "version": "4.3.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxx64/4.3.0/mirrg.kotlin.helium-kotlin-2-1-linuxx64-4.3.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxx64",
        "version": "4.3.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxx64/4.3.0/mirrg.kotlin.helium-kotlin-2-1-linuxx64-4.3.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxx64",
        "version": "4.3.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-mingwx64/4.3.0/mirrg.kotlin.helium-kotlin-2-1-mingwx64-4.3.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-mingwx64",
        "version": "4.3.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-mingwx64/4.3.0/mirrg.kotlin.helium-kotlin-2-1-mingwx64-4.3.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-mingwx64",
        "version": "4.3.0"
      }
    }
  ]
}
