{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-2/4.3.0/mirrg.kotlin.helium-kotlin-2-2-4.3.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-2",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-js-4.3.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-2-js-4.3.0.klib",
          "size": 28401,
          "sha512": "19fefaa637d70d8442019cb72997f1ffc27fab7dec9524bcdb6b7d74d89a9d769d217fb67ed68ec0036398436cdf857c91f4c734dc8b58c8fba73d708b70e992",
          "sha256": "9a41ed05f7a02254af25eb689e10ffc99a0ec7e07a1fef740c3fc7f4a3a47517",
          "sha1": "92f359a2165a3456fe473efb6580feaa7299efa2",
          "md5": "787d42751c90cecebb043851ce496e79"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-js-4.3.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-2-js-4.3.0.klib",
          "size": 28401,
          "sha512": "19fefaa637d70d8442019cb72997f1ffc27fab7dec9524bcdb6b7d74d89a9d769d217fb67ed68ec0036398436cdf857c91f4c734dc8b58c8fba73d708b70e992",
          "sha256": "9a41ed05f7a02254af25eb689e10ffc99a0ec7e07a1fef740c3fc7f4a3a47517",
          "sha1": "92f359a2165a3456fe473efb6580feaa7299efa2",
          "md5": "787d42751c90cecebb043851ce496e79"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-js-4.3.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-js-4.3.0-sources.jar",
          "size": 3797,
          "sha512": "10b2749af16fe3e272cc741a193ab9d8c8b635c44c4c4ddd483ba3a737544ff39ec390e5f3d2b3e99d397e74fd7770183a49dde6c277651d9bbfdc672c95e2e5",
          "sha256": "f774c0348ba67ca581353115b1eea93207dd3c1dc88a78548caf7ce81a7780e3",
          "sha1": "c1e847f8c4faf3dfb9da97744313ee5a27cdfb21",
          "md5": "73401ad3093fe01879126c8e622408d9"
        }
      ]
    }
  ]
}
