{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-9/4.2.0/mirrg.kotlin.helium-kotlin-1-9-4.2.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-9",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-9-linuxx64-4.2.0.klib",
          "size": 24925,
          "sha512": "24fe474edc988532ee081dceb12a5f46764d666cafee9bec80bffe0ffe25c3ca1516a9b6937b5d037fb9c87f7b20ed63c81f1f7afaa59216da1dab9b80cb1c14",
          "sha256": "b8b6f873c477665d9c6dec674b28355137326e03b5d176c741ebbfd7b5dc7add",
          "sha1": "b25bdb1a8d40b0bb48217b1dcaab35700be7b6c3",
          "md5": "367619c9a1e004c5cdc0e5b9d1af4b43"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-linuxx64-4.2.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-linuxx64-4.2.0-sources.jar",
          "size": 3668,
          "sha512": "88e69b0a944fe896966342f4108ed2effa9da1b5deab08ba414424fcd1cd64e81a5ac3ef5b509c8a451141dbba19abefcaa8256205b62336fb6c341b42573ea2",
          "sha256": "2e82a2c8712db07e240ef87e1102ac3eaf7d9091d72119be618ec1204fbc8d90",
          "sha1": "a85c6845aed7e8355126fedebfd007e6a91dafca",
          "md5": "4893911cd7d818cc631dbbd20993c8e4"
        }
      ]
    }
  ]
}
