{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-0/4.4.0/mirrg.kotlin.helium-kotlin-2-0-4.4.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-0",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-js-4.4.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-0-js-4.4.0.klib",
          "size": 29401,
          "sha512": "6b2506f3b1215e45ba880eb1334a16f99b60f05bfd1d87f8568c130b4c05d0b02009ab78d947e1757a423a04ea7327507c437c21f1ac3d1e02774cb32caa3931",
          "sha256": "a8eae28f33b72525e535a4f4798d808cdca836ac06888b6c217992608b261b73",
          "sha1": "3555f05506abcb147007bb594835c628741de989",
          "md5": "03046f634808a55eaeb6e61ca3b0a13e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-js-4.4.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-0-js-4.4.0.klib",
          "size": 29401,
          "sha512": "6b2506f3b1215e45ba880eb1334a16f99b60f05bfd1d87f8568c130b4c05d0b02009ab78d947e1757a423a04ea7327507c437c21f1ac3d1e02774cb32caa3931",
          "sha256": "a8eae28f33b72525e535a4f4798d808cdca836ac06888b6c217992608b261b73",
          "sha1": "3555f05506abcb147007bb594835c628741de989",
          "md5": "03046f634808a55eaeb6e61ca3b0a13e"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-js-4.4.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-js-4.4.0-sources.jar",
          "size": 4028,
          "sha512": "5ef4b0c357557f9dbd9b211aeb51bc8ee7c816125ccb0f977761f621ea10c6e0f9b11a37ed28036a916f582c550f8136405c1c51d6eeadc15f367df9398b8dfd",
          "sha256": "dfe319ee38219a70fd6a327c62442fa5c9f7300902beacfcd24ac86783d7ee8a",
          "sha1": "4c1e2fcd3897c74d99fbe3411ba98bf3744d189a",
          "md5": "f9cf3bbfc427f9ab74b6359e49c7133d"
        }
      ]
    }
  ]
}
