// DO NOT EDIT THIS FILE MANUALLY! IT IS AUTOGENERATED!

import org.gradle.kotlin.dsl.support.uppercaseFirstChar
import org.jetbrains.kotlin.gradle.plugin.KotlinSourceSet

plugins {
    kotlin("multiplatform") version "2.1.21"
    `maven-publish`
    id("build-logic")
}

group = "mirrg.kotlin"
val envVersion = System.getenv("VERSION") ?: ""
if (envVersion.isNotBlank()) version = envVersion

val outerProjectDirectory = rootProject.layout.projectDirectory.dir("..")

repositories {
    mavenCentral()
}

kotlin {
    jvm()
    js {
        browser()
        nodejs()
    }
    linuxX64()
    linuxArm64()
    mingwX64()
    //macosX64()
    //macosArm64()
    //androidNativeArm32()
    //androidNativeArm64()
    //androidNativeX86()
    //androidNativeX64()
    //iosX64()
    //iosArm64()
    //iosSimulatorArm64()
    //tvosX64()
    //tvosArm64()
    //tvosSimulatorArm64()
    //watchosX64()
    //watchosArm64()
    //watchosSimulatorArm64()
    //watchosArm32()
    //@OptIn(org.jetbrains.kotlin.gradle.targets.js.dsl.ExperimentalWasmDsl::class)
    //wasmJs {
    //    browser()
    //    nodejs()
    //    d8()
    //}
    //@OptIn(org.jetbrains.kotlin.gradle.targets.js.dsl.ExperimentalWasmDsl::class)
    //wasmWasi()

    fun KotlinSourceSet.setGeneration() {
        val sourceSetName = name
        val generateTask = project.tasks.register<Sync>("generate${sourceSetName.uppercaseFirstChar()}KotlinSources") {
            group = "generation"
            into(project.layout.projectDirectory.dir("generated/$sourceSetName/kotlin"))
            from(outerProjectDirectory.dir("template/src/$sourceSetName/template")) {
                include("**/*.txt")
                rename { it.removeSuffix(".txt") }
                filter { Template.evaluate(it, Template.Arguments("2.1.21")) }
            }
        }
        kotlin.setSrcDirs(listOf(generateTask))
    }

    sourceSets {
        val commonMain by getting {
            setGeneration()
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
            }
            setGeneration()
        }
    }
}

tasks.withType<Jar>().configureEach {
    from(outerProjectDirectory.file("LICENSE")) {
        into("META-INF")
        rename { "LICENSE" }
    }
}

publishing {
    repositories {
        maven {
            name = "localFolder"
            val envMavenDir = System.getenv("MAVEN_DIR") ?: ""
            url = if (envMavenDir.isNotBlank()) uri(file(envMavenDir)) else uri(outerProjectDirectory.dir("maven"))
        }
    }
}
