// DO NOT EDIT THIS FILE MANUALLY! IT IS AUTOGENERATED!

import org.gradle.kotlin.dsl.support.uppercaseFirstChar

plugins {
    kotlin("multiplatform") version "2.1.21"
    `maven-publish`
    id("build-logic")
}

group = "mirrg.kotlin"
val envVersion = System.getenv("VERSION") ?: ""
if (envVersion.isNotBlank()) version = envVersion

val outerProjectDirectory = rootProject.layout.projectDirectory.dir("..")

repositories {
    mavenCentral()
}

tasks.register("generate") {
    group = "generation"
}

kotlin {
    jvm {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
        }
    }
    js {
        browser()
        nodejs()
    }
    linuxX64()
    linuxArm64()
    mingwX64()
    //macosX64()
    //macosArm64()
    //androidNativeArm32()
    //androidNativeArm64()
    //androidNativeX86()
    //androidNativeX64()
    //iosX64()
    //iosArm64()
    //iosSimulatorArm64()
    //tvosX64()
    //tvosArm64()
    //tvosSimulatorArm64()
    //watchosX64()
    //watchosArm64()
    //watchosSimulatorArm64()
    //watchosArm32()
    //@OptIn(org.jetbrains.kotlin.gradle.targets.js.dsl.ExperimentalWasmDsl::class)
    //wasmJs {
    //    browser()
    //    nodejs()
    //    d8()
    //}
    //@OptIn(org.jetbrains.kotlin.gradle.targets.js.dsl.ExperimentalWasmDsl::class)
    //wasmWasi()

    fun org.jetbrains.kotlin.gradle.plugin.KotlinSourceSet.setGeneration() {
        val sourceSetName = name
        val generateTask = project.tasks.register("generate${sourceSetName.uppercaseFirstChar()}KotlinSources") {
            group = "generation"

            val inputDir = outerProjectDirectory.dir("template/src/$sourceSetName/template")
            val outputDir = project.layout.projectDirectory.dir("generated/$sourceSetName/kotlin")

            val inputFiles = project.fileTree(inputDir) { include("**/*.txt") }
            inputs.files(inputFiles)
            outputs.dir(outputDir)

            doLast {
                val oldOutputFiles: MutableList<File> = project.fileTree(outputDir).filter { it.isFile }.toMutableList()
                inputFiles.forEach { inputFile ->
                    val outputFile = outputDir.file(inputFile.relativeTo(inputDir.asFile).invariantSeparatorsPath.removeSuffix(".txt")).asFile

                    println("Generating $outputFile")
                    val input = inputFile.readText()
                    val arguments = Template.Arguments(
                        versionString = "2.1.21",
                        parameters = mapOf(),
                    )
                    val output = Template.evaluate(input, arguments)
                    outputFile.parentFile.mkdirs()
                    outputFile.writeText(output)

                    oldOutputFiles.remove(outputFile)
                }
                oldOutputFiles.forEach {
                    println("Deleting $it")
                    it.delete()
                }
            }
        }
        project.tasks.named("generate").configure { dependsOn(generateTask) }
        kotlin.setSrcDirs(listOf(generateTask))
    }

    sourceSets {
        val commonMain by getting {
            setGeneration()
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
            }
            setGeneration()
        }
    }
}

tasks.withType<Jar>().configureEach {
    from(outerProjectDirectory.file("LICENSE")) {
        into("META-INF")
        rename { "LICENSE" }
    }
}

publishing {
    repositories {
        maven {
            name = "localFolder"
            val envMavenDir = System.getenv("MAVEN_DIR") ?: ""
            url = if (envMavenDir.isNotBlank()) uri(file(envMavenDir)) else uri(outerProjectDirectory.dir("maven"))
        }
    }
}
