{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-7/4.4.0/mirrg.kotlin.helium-kotlin-1-7-4.4.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-7",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-7-jvm-4.4.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-7-jvm-4.4.0.jar",
          "size": 21304,
          "sha512": "3cfb2c7f080ba037d1b01c2b7f5a06e0d5c55d0fcfc9cbd309f416092c5083b6b5bb1f33dc6bff3214e1744af5c902805c53563c88a8ea47aa98e6621e6a7c47",
          "sha256": "32fdad690da24e6b5da0b461d55fecd44f84c89c3f0a1182d91150f40c03b894",
          "sha1": "aadb3dd01ca727e1ece13f3f2f956192079b2cbd",
          "md5": "ac13a07b7e0a8ef15f7d561b705f0272"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-7-jvm-4.4.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-7-jvm-4.4.0.jar",
          "size": 21304,
          "sha512": "3cfb2c7f080ba037d1b01c2b7f5a06e0d5c55d0fcfc9cbd309f416092c5083b6b5bb1f33dc6bff3214e1744af5c902805c53563c88a8ea47aa98e6621e6a7c47",
          "sha256": "32fdad690da24e6b5da0b461d55fecd44f84c89c3f0a1182d91150f40c03b894",
          "sha1": "aadb3dd01ca727e1ece13f3f2f956192079b2cbd",
          "md5": "ac13a07b7e0a8ef15f7d561b705f0272"
        }
      ]
    }
  ]
}
