{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-8/4.3.0/mirrg.kotlin.helium-kotlin-1-8-4.3.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-8",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8-js-4.3.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-8-js-4.3.0.klib",
          "size": 26845,
          "sha512": "95e52ccb58efd852ef390fcd449a6c069e96564a33fc311409e83ea37382e3e861a4a14a6591784714dcf7b187cfa5d26949207ee382bafef7c64e3120e9cb07",
          "sha256": "3c9f5d93406768f2cffc5da78ffd59d2046e25d3e9c96c0f28f91f6a976c7fe4",
          "sha1": "be7c72388b1347bf78ec6c210e319519d0b3a29b",
          "md5": "3b5e792a24206bf19b9751b4427d3928"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8-js-4.3.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-8-js-4.3.0.klib",
          "size": 26845,
          "sha512": "95e52ccb58efd852ef390fcd449a6c069e96564a33fc311409e83ea37382e3e861a4a14a6591784714dcf7b187cfa5d26949207ee382bafef7c64e3120e9cb07",
          "sha256": "3c9f5d93406768f2cffc5da78ffd59d2046e25d3e9c96c0f28f91f6a976c7fe4",
          "sha1": "be7c72388b1347bf78ec6c210e319519d0b3a29b",
          "md5": "3b5e792a24206bf19b9751b4427d3928"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8-js-4.3.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-8-js-4.3.0-sources.jar",
          "size": 3797,
          "sha512": "10b2749af16fe3e272cc741a193ab9d8c8b635c44c4c4ddd483ba3a737544ff39ec390e5f3d2b3e99d397e74fd7770183a49dde6c277651d9bbfdc672c95e2e5",
          "sha256": "f774c0348ba67ca581353115b1eea93207dd3c1dc88a78548caf7ce81a7780e3",
          "sha1": "c1e847f8c4faf3dfb9da97744313ee5a27cdfb21",
          "md5": "73401ad3093fe01879126c8e622408d9"
        }
      ]
    }
  ]
}
