{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-0/4.1.0/mirrg.kotlin.helium-kotlin-2-0-4.1.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-0",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.1.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.1.0.jar",
          "size": 18187,
          "sha512": "179d1e1ed8fb14150e8b340dca19852d6259f3df2a34098e5ea8ac125f41e8b31f685226a8b862d6b3a420dc120935774b761baf82e24ea40e059bcf3898a62d",
          "sha256": "155ff2306606fae274241d6d2f184d5fa2b5ee2e83ec426964a9dde0cc10d03b",
          "sha1": "ea058619fd1c54ea6ec823b10145758181561ca1",
          "md5": "7c65a9b1eb3e765a1df17997ad5338b0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.1.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.1.0.jar",
          "size": 18187,
          "sha512": "179d1e1ed8fb14150e8b340dca19852d6259f3df2a34098e5ea8ac125f41e8b31f685226a8b862d6b3a420dc120935774b761baf82e24ea40e059bcf3898a62d",
          "sha256": "155ff2306606fae274241d6d2f184d5fa2b5ee2e83ec426964a9dde0cc10d03b",
          "sha1": "ea058619fd1c54ea6ec823b10145758181561ca1",
          "md5": "7c65a9b1eb3e765a1df17997ad5338b0"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.1.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.1.0-sources.jar",
          "size": 3626,
          "sha512": "9d61d877e6915037ec99a454bd9a03217b94c677f0954c98105c711a6ad9855c1ef41303f332b14dc22af30e0f5a839630dbf2b6b386f66aab5c4913ae24fafd",
          "sha256": "2071b17f6d792fafadbad4b4f751ed40c13ebd37f6834a7a94308746cba7b453",
          "sha1": "7d434e1d3ec8b0e1838321bc7954628c5d6f0677",
          "md5": "186ba7c2ee70500e0e848017ec51b678"
        }
      ]
    }
  ]
}
