{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-8/4.1.0/mirrg.kotlin.helium-kotlin-1-8-4.1.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-8",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-8-linuxx64-4.1.0.klib",
          "size": 22640,
          "sha512": "c5dcd122f4210193aac5653f9c65bdf0cda4bf0305e6075c34ba47fa58c14096ac4156e40c1a41bb2594208e79ef139b9fcbf67a7fb8af2b3e15db7f68d77124",
          "sha256": "71d2b0916a78648be2fdc8984c3645bcecc4bf1427b1f77b5a9c7674afa5da3a",
          "sha1": "b8c8aa2fd1ffd92522fc7e60c53a9794dee6b1e7",
          "md5": "8c22cc331ccc09c15f5c654d434ada60"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8-linuxx64-4.1.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-8-linuxx64-4.1.0-sources.jar",
          "size": 3626,
          "sha512": "9d61d877e6915037ec99a454bd9a03217b94c677f0954c98105c711a6ad9855c1ef41303f332b14dc22af30e0f5a839630dbf2b6b386f66aab5c4913ae24fafd",
          "sha256": "2071b17f6d792fafadbad4b4f751ed40c13ebd37f6834a7a94308746cba7b453",
          "sha1": "7d434e1d3ec8b0e1838321bc7954628c5d6f0677",
          "md5": "186ba7c2ee70500e0e848017ec51b678"
        }
      ]
    }
  ]
}
