{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-2/4.4.0/mirrg.kotlin.helium-kotlin-2-2-4.4.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-2",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-js-4.4.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-2-js-4.4.0.klib",
          "size": 29607,
          "sha512": "cdfd6560ad44f20fbd465dc437e5b5d925f4d2de30ec27bba3b07921102a285ebb8881d5699dd6d5baf94eff70a1bccffc93b15b14cf9e7d2654e7d67fce2bc1",
          "sha256": "4a39891306fb3f752ff79b9aff6df32f8e50537f9c20eadf738ec5bbd4534844",
          "sha1": "9b6eb1645e4d73e8ef97c7525ae693f67877804e",
          "md5": "702b19d95618faba9a4e547016f6a420"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-js-4.4.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-2-js-4.4.0.klib",
          "size": 29607,
          "sha512": "cdfd6560ad44f20fbd465dc437e5b5d925f4d2de30ec27bba3b07921102a285ebb8881d5699dd6d5baf94eff70a1bccffc93b15b14cf9e7d2654e7d67fce2bc1",
          "sha256": "4a39891306fb3f752ff79b9aff6df32f8e50537f9c20eadf738ec5bbd4534844",
          "sha1": "9b6eb1645e4d73e8ef97c7525ae693f67877804e",
          "md5": "702b19d95618faba9a4e547016f6a420"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-js-4.4.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-js-4.4.0-sources.jar",
          "size": 4028,
          "sha512": "5ef4b0c357557f9dbd9b211aeb51bc8ee7c816125ccb0f977761f621ea10c6e0f9b11a37ed28036a916f582c550f8136405c1c51d6eeadc15f367df9398b8dfd",
          "sha256": "dfe319ee38219a70fd6a327c62442fa5c9f7300902beacfcd24ac86783d7ee8a",
          "sha1": "4c1e2fcd3897c74d99fbe3411ba98bf3744d189a",
          "md5": "f9cf3bbfc427f9ab74b6359e49c7133d"
        }
      ]
    }
  ]
}
