{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium/2.0.0/mirrg.kotlin.helium-2.0.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium.klib",
          "url": "mirrg.kotlin.helium-mingwx64-2.0.0.klib",
          "size": 22914,
          "sha512": "67e7f91802ce6fd2452551407d8f7965f4537906996b2b06bc1a7498caee80d09abb9a125cad02e4d58c950e80cd550eb5f93e9d69911580338fe6f7ab4d6d2a",
          "sha256": "242f6d3a2db22c0b36e25d7a8e0a8f9d71ac70bcc9ffd5c9263ffee740bc2e77",
          "sha1": "d26b0868a9ac9af09961bfd7f3c187e04ac15b0d",
          "md5": "7769c6932fe9a618eccbd300b78c3d3d"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-mingwx64-2.0.0-sources.jar",
          "url": "mirrg.kotlin.helium-mingwx64-2.0.0-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    }
  ]
}
