{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-0/4.3.0/mirrg.kotlin.helium-kotlin-2-0-4.3.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-0",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-0-linuxarm64-4.3.0.klib",
          "size": 25300,
          "sha512": "2da3a603d59383557f1b649ca6d70f44b7a03c8e1474bc704a2f535e19c480bf2583a94f08aedc6ce2dfc8b1bc89a5724118923f1299d6ca06be55815369b27a",
          "sha256": "2544d56c092870f1ecfcf23e6192511862a73388f6918692636e54983add3802",
          "sha1": "cdac3b307c9ca5ba50e791c40d15d24feb28cd83",
          "md5": "df05f2176f46d744b28e2c494da5b0b0"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-linuxarm64-4.3.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-linuxarm64-4.3.0-sources.jar",
          "size": 3797,
          "sha512": "10b2749af16fe3e272cc741a193ab9d8c8b635c44c4c4ddd483ba3a737544ff39ec390e5f3d2b3e99d397e74fd7770183a49dde6c277651d9bbfdc672c95e2e5",
          "sha256": "f774c0348ba67ca581353115b1eea93207dd3c1dc88a78548caf7ce81a7780e3",
          "sha1": "c1e847f8c4faf3dfb9da97744313ee5a27cdfb21",
          "md5": "73401ad3093fe01879126c8e622408d9"
        }
      ]
    }
  ]
}
