{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-2/4.1.0/mirrg.kotlin.helium-kotlin-2-2-4.1.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-2",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.1.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.1.0.jar",
          "size": 18168,
          "sha512": "dfa62f25ff3dbddd2222c16e882dfd25eb085d1a86d000fdd0956a2429be73fb29eb03e1abc7288156cd8eebe536cd386b9666a66c0fe1018280b6845684947e",
          "sha256": "eb81a0e6c76b3ab3fc0a9ad6b8ff40bafeac4cbd867fa7b676c42d26c7328a3e",
          "sha1": "c639f197d484da8369d4579e45e12cbf9e51670d",
          "md5": "a201b1892d321b2f154efbd1fb2ace35"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.1.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.1.0.jar",
          "size": 18168,
          "sha512": "dfa62f25ff3dbddd2222c16e882dfd25eb085d1a86d000fdd0956a2429be73fb29eb03e1abc7288156cd8eebe536cd386b9666a66c0fe1018280b6845684947e",
          "sha256": "eb81a0e6c76b3ab3fc0a9ad6b8ff40bafeac4cbd867fa7b676c42d26c7328a3e",
          "sha1": "c639f197d484da8369d4579e45e12cbf9e51670d",
          "md5": "a201b1892d321b2f154efbd1fb2ace35"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.1.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.1.0-sources.jar",
          "size": 3626,
          "sha512": "9d61d877e6915037ec99a454bd9a03217b94c677f0954c98105c711a6ad9855c1ef41303f332b14dc22af30e0f5a839630dbf2b6b386f66aab5c4913ae24fafd",
          "sha256": "2071b17f6d792fafadbad4b4f751ed40c13ebd37f6834a7a94308746cba7b453",
          "sha1": "7d434e1d3ec8b0e1838321bc7954628c5d6f0677",
          "md5": "186ba7c2ee70500e0e848017ec51b678"
        }
      ]
    }
  ]
}
