{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-0/4.4.0/mirrg.kotlin.helium-kotlin-2-0-4.4.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-0",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.4.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.4.0.jar",
          "size": 19166,
          "sha512": "de4bbc3a8c251e24f737d1651c2268eb5c87d0b9c6558fc313e81c8eac6e216c5884dbc7029116009e1f9a918b1a2ea7232537eaea57c588f66e641e6b4b256d",
          "sha256": "18b053edc75949352f21182cccc243a5f0dc718734f39e797f2a11ad2aeecbc2",
          "sha1": "057bf82b0c878141386e7ca93fafeebfb6b68f37",
          "md5": "1764a177e81c33d75b7b4adbaa25bc2a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.4.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.4.0.jar",
          "size": 19166,
          "sha512": "de4bbc3a8c251e24f737d1651c2268eb5c87d0b9c6558fc313e81c8eac6e216c5884dbc7029116009e1f9a918b1a2ea7232537eaea57c588f66e641e6b4b256d",
          "sha256": "18b053edc75949352f21182cccc243a5f0dc718734f39e797f2a11ad2aeecbc2",
          "sha1": "057bf82b0c878141386e7ca93fafeebfb6b68f37",
          "md5": "1764a177e81c33d75b7b4adbaa25bc2a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.4.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.4.0-sources.jar",
          "size": 4028,
          "sha512": "5ef4b0c357557f9dbd9b211aeb51bc8ee7c816125ccb0f977761f621ea10c6e0f9b11a37ed28036a916f582c550f8136405c1c51d6eeadc15f367df9398b8dfd",
          "sha256": "dfe319ee38219a70fd6a327c62442fa5c9f7300902beacfcd24ac86783d7ee8a",
          "sha1": "4c1e2fcd3897c74d99fbe3411ba98bf3744d189a",
          "md5": "f9cf3bbfc427f9ab74b6359e49c7133d"
        }
      ]
    }
  ]
}
