{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-9/4.2.0/mirrg.kotlin.helium-kotlin-1-9-4.2.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-9",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-js-4.2.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-9-js-4.2.0.klib",
          "size": 27493,
          "sha512": "b66a07765e12bfcc96e125a871ff63b678e582b983e18865c7888a8849904309cb0cba02888b013c36856f4727f971c67d2d2b2888065f28fc82c02f21721285",
          "sha256": "68a97c85b35e9ed12ca563d7e26779e491b3796bc680aed67c085a6365288a7b",
          "sha1": "fc0d7e8587a59e7b32ac2e29ffa0c7e64d948c54",
          "md5": "b04eedecd36b7bb43e9211968652904a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-js-4.2.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-9-js-4.2.0.klib",
          "size": 27493,
          "sha512": "b66a07765e12bfcc96e125a871ff63b678e582b983e18865c7888a8849904309cb0cba02888b013c36856f4727f971c67d2d2b2888065f28fc82c02f21721285",
          "sha256": "68a97c85b35e9ed12ca563d7e26779e491b3796bc680aed67c085a6365288a7b",
          "sha1": "fc0d7e8587a59e7b32ac2e29ffa0c7e64d948c54",
          "md5": "b04eedecd36b7bb43e9211968652904a"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-js-4.2.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-js-4.2.0-sources.jar",
          "size": 3668,
          "sha512": "88e69b0a944fe896966342f4108ed2effa9da1b5deab08ba414424fcd1cd64e81a5ac3ef5b509c8a451141dbba19abefcaa8256205b62336fb6c341b42573ea2",
          "sha256": "2e82a2c8712db07e240ef87e1102ac3eaf7d9091d72119be618ec1204fbc8d90",
          "sha1": "a85c6845aed7e8355126fedebfd007e6a91dafca",
          "md5": "4893911cd7d818cc631dbbd20993c8e4"
        }
      ]
    }
  ]
}
