{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium/3.0.0/mirrg.kotlin.helium-3.0.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-js-3.0.0.klib",
          "url": "mirrg.kotlin.helium-js-3.0.0.klib",
          "size": 25898,
          "sha512": "a8c66260b0d6bf55785cf79d50f4e46c824774a1a2724703343055bbf2b7d5a0a98dfc61a94d9d84855345be5296f568eb7a18852cc00f7b58cdcdfd9db56eb2",
          "sha256": "b6c2fb4cdbd41f81086f4196e83134ea31ec57e8a4d1dec842f3f67505cc7551",
          "sha1": "cd3f62e8572703c1795c99403a24b227bb114a1a",
          "md5": "3d7997de4e84f22fcba59177c7dac9a2"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-js-3.0.0.klib",
          "url": "mirrg.kotlin.helium-js-3.0.0.klib",
          "size": 25898,
          "sha512": "a8c66260b0d6bf55785cf79d50f4e46c824774a1a2724703343055bbf2b7d5a0a98dfc61a94d9d84855345be5296f568eb7a18852cc00f7b58cdcdfd9db56eb2",
          "sha256": "b6c2fb4cdbd41f81086f4196e83134ea31ec57e8a4d1dec842f3f67505cc7551",
          "sha1": "cd3f62e8572703c1795c99403a24b227bb114a1a",
          "md5": "3d7997de4e84f22fcba59177c7dac9a2"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-js-3.0.0-sources.jar",
          "url": "mirrg.kotlin.helium-js-3.0.0-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    }
  ]
}
