{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-9/4.3.0/mirrg.kotlin.helium-kotlin-1-9-4.3.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-9",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-js-4.3.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-9-js-4.3.0.klib",
          "size": 28892,
          "sha512": "2c8e2a4305fd66c33719503f24f7debd38716d2fd6cf50010e2a97aba7d59be000a31d40cb6b2c4ef33baaac03b385be47dc1f23ec42f5d90bf5fee8be8f54fd",
          "sha256": "c2f5023a940d0d08f5b5e85a1b6ddbf1397102702a34578582cb295cc82b83b5",
          "sha1": "b7873e3eff38dba2850a09b65e93c675006b6111",
          "md5": "f08e51852b45ed6dac820f4eefe4fe07"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-js-4.3.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-9-js-4.3.0.klib",
          "size": 28892,
          "sha512": "2c8e2a4305fd66c33719503f24f7debd38716d2fd6cf50010e2a97aba7d59be000a31d40cb6b2c4ef33baaac03b385be47dc1f23ec42f5d90bf5fee8be8f54fd",
          "sha256": "c2f5023a940d0d08f5b5e85a1b6ddbf1397102702a34578582cb295cc82b83b5",
          "sha1": "b7873e3eff38dba2850a09b65e93c675006b6111",
          "md5": "f08e51852b45ed6dac820f4eefe4fe07"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-js-4.3.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-js-4.3.0-sources.jar",
          "size": 3797,
          "sha512": "10b2749af16fe3e272cc741a193ab9d8c8b635c44c4c4ddd483ba3a737544ff39ec390e5f3d2b3e99d397e74fd7770183a49dde6c277651d9bbfdc672c95e2e5",
          "sha256": "f774c0348ba67ca581353115b1eea93207dd3c1dc88a78548caf7ce81a7780e3",
          "sha1": "c1e847f8c4faf3dfb9da97744313ee5a27cdfb21",
          "md5": "73401ad3093fe01879126c8e622408d9"
        }
      ]
    }
  ]
}
