{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-0/4.2.0/mirrg.kotlin.helium-kotlin-2-0-4.2.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-0",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.2.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.2.0.jar",
          "size": 18388,
          "sha512": "e1c5e5a817e1b0af0543a296d4c3c34d05d4b6af73e898966c39a9574b5a00befc09d6e4f69e24ab956fab6514ccd547e753ad2b68e047241f530a22ea5a0b0d",
          "sha256": "d963c98d9d77fc2e6e9caab941dc41c6d3b5d96e7ac5d7055fe0f26d1572d232",
          "sha1": "ec3237da1ffab6553491826ef4ce38d6c2b22c42",
          "md5": "6853bfe22d47e62c45e82a873defeba3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.2.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.2.0.jar",
          "size": 18388,
          "sha512": "e1c5e5a817e1b0af0543a296d4c3c34d05d4b6af73e898966c39a9574b5a00befc09d6e4f69e24ab956fab6514ccd547e753ad2b68e047241f530a22ea5a0b0d",
          "sha256": "d963c98d9d77fc2e6e9caab941dc41c6d3b5d96e7ac5d7055fe0f26d1572d232",
          "sha1": "ec3237da1ffab6553491826ef4ce38d6c2b22c42",
          "md5": "6853bfe22d47e62c45e82a873defeba3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.2.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-jvm-4.2.0-sources.jar",
          "size": 3668,
          "sha512": "88e69b0a944fe896966342f4108ed2effa9da1b5deab08ba414424fcd1cd64e81a5ac3ef5b509c8a451141dbba19abefcaa8256205b62336fb6c341b42573ea2",
          "sha256": "2e82a2c8712db07e240ef87e1102ac3eaf7d9091d72119be618ec1204fbc8d90",
          "sha1": "a85c6845aed7e8355126fedebfd007e6a91dafca",
          "md5": "4893911cd7d818cc631dbbd20993c8e4"
        }
      ]
    }
  ]
}
