{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-8/4.1.0/mirrg.kotlin.helium-kotlin-1-8-4.1.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-8",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8-jvm-4.1.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-8-jvm-4.1.0.jar",
          "size": 20463,
          "sha512": "30076d390e0f8c8813ad55aecd379444573012d1a9bf160fc2c3244c98c235339e91f8e1ac76cbb2e188a829ef4ce5d9f61b1a3c9cd0f0715cf5855b1aa1e04a",
          "sha256": "8a44a2b48a2d08ea0e83603ba00fddc12b2d423a86168ff270b55ccc625637ea",
          "sha1": "801f61394488e5719b647593820c60f15ee66d5a",
          "md5": "4fb5176d0a87acebfd4441cac42c8cfc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8-jvm-4.1.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-8-jvm-4.1.0.jar",
          "size": 20463,
          "sha512": "30076d390e0f8c8813ad55aecd379444573012d1a9bf160fc2c3244c98c235339e91f8e1ac76cbb2e188a829ef4ce5d9f61b1a3c9cd0f0715cf5855b1aa1e04a",
          "sha256": "8a44a2b48a2d08ea0e83603ba00fddc12b2d423a86168ff270b55ccc625637ea",
          "sha1": "801f61394488e5719b647593820c60f15ee66d5a",
          "md5": "4fb5176d0a87acebfd4441cac42c8cfc"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8-jvm-4.1.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-8-jvm-4.1.0-sources.jar",
          "size": 3626,
          "sha512": "9d61d877e6915037ec99a454bd9a03217b94c677f0954c98105c711a6ad9855c1ef41303f332b14dc22af30e0f5a839630dbf2b6b386f66aab5c4913ae24fafd",
          "sha256": "2071b17f6d792fafadbad4b4f751ed40c13ebd37f6834a7a94308746cba7b453",
          "sha1": "7d434e1d3ec8b0e1838321bc7954628c5d6f0677",
          "md5": "186ba7c2ee70500e0e848017ec51b678"
        }
      ]
    }
  ]
}
