{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-1/4.2.0/mirrg.kotlin.helium-kotlin-2-1-4.2.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-1",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.2.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.2.0.jar",
          "size": 18395,
          "sha512": "a472264c9e6feeeaf2018c983b28b56bbee0e527274a1944769fa78c95af575265256dcfd630ce1e4397c850277501da10d5e5dc8dd38337bb082d65fc5b5c51",
          "sha256": "9be9abb0d3e12e5eac10304f273316818d8701b5eedf2770f2a71205b6adcbaa",
          "sha1": "194844bf5664f2597f018f41d541b9b969ba8dae",
          "md5": "8d84cf335a92267672ee8ca3ec6efc7c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.2.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.2.0.jar",
          "size": 18395,
          "sha512": "a472264c9e6feeeaf2018c983b28b56bbee0e527274a1944769fa78c95af575265256dcfd630ce1e4397c850277501da10d5e5dc8dd38337bb082d65fc5b5c51",
          "sha256": "9be9abb0d3e12e5eac10304f273316818d8701b5eedf2770f2a71205b6adcbaa",
          "sha1": "194844bf5664f2597f018f41d541b9b969ba8dae",
          "md5": "8d84cf335a92267672ee8ca3ec6efc7c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.2.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.2.0-sources.jar",
          "size": 3668,
          "sha512": "88e69b0a944fe896966342f4108ed2effa9da1b5deab08ba414424fcd1cd64e81a5ac3ef5b509c8a451141dbba19abefcaa8256205b62336fb6c341b42573ea2",
          "sha256": "2e82a2c8712db07e240ef87e1102ac3eaf7d9091d72119be618ec1204fbc8d90",
          "sha1": "a85c6845aed7e8355126fedebfd007e6a91dafca",
          "md5": "4893911cd7d818cc631dbbd20993c8e4"
        }
      ]
    }
  ]
}
