{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-2/4.0.1/mirrg.kotlin.helium-kotlin-2-2-4.0.1.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-2",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-js-4.0.1.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-2-js-4.0.1.klib",
          "size": 26063,
          "sha512": "500e9aba43c3ff107d26102e3f3b91f4d3cc799b433905e54c6848b7b8d81de25e1f187e7cc2f3095f95cc2eb128f4b0c105e8c5e58044be52a9c3ee66ead164",
          "sha256": "4e9863015cc51ca6c0817d4ca8f1ecba63af288df2036c7b6c5a5846af9dcd15",
          "sha1": "7f98d66e4b24aaf7fb979b58d238aa8c57ddc011",
          "md5": "944a1c2ba1622402c2c188a136dec3b8"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-js-4.0.1.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-2-js-4.0.1.klib",
          "size": 26063,
          "sha512": "500e9aba43c3ff107d26102e3f3b91f4d3cc799b433905e54c6848b7b8d81de25e1f187e7cc2f3095f95cc2eb128f4b0c105e8c5e58044be52a9c3ee66ead164",
          "sha256": "4e9863015cc51ca6c0817d4ca8f1ecba63af288df2036c7b6c5a5846af9dcd15",
          "sha1": "7f98d66e4b24aaf7fb979b58d238aa8c57ddc011",
          "md5": "944a1c2ba1622402c2c188a136dec3b8"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-js-4.0.1-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-js-4.0.1-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    }
  ]
}
