{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-0/4.1.0/mirrg.kotlin.helium-kotlin-2-0-4.1.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-0",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-js-4.1.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-0-js-4.1.0.klib",
          "size": 26449,
          "sha512": "936041d525277e20d99b2136396167cf1a3631c4af02d65295dda3b04a6310876baa2dda38619212520da37c4ef903df587c3c333ba3a738a7bd858ef5c18c26",
          "sha256": "c40251ede3c2f0af7ff84943ebb4d54e067072f8d7940b9ab2cd4cfd4072553b",
          "sha1": "1611da6ac1ce1b6ef98a370373d3c941cc56be16",
          "md5": "676d7d55b095a830f5fb849a9e82d0ef"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-js-4.1.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-0-js-4.1.0.klib",
          "size": 26449,
          "sha512": "936041d525277e20d99b2136396167cf1a3631c4af02d65295dda3b04a6310876baa2dda38619212520da37c4ef903df587c3c333ba3a738a7bd858ef5c18c26",
          "sha256": "c40251ede3c2f0af7ff84943ebb4d54e067072f8d7940b9ab2cd4cfd4072553b",
          "sha1": "1611da6ac1ce1b6ef98a370373d3c941cc56be16",
          "md5": "676d7d55b095a830f5fb849a9e82d0ef"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-js-4.1.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-js-4.1.0-sources.jar",
          "size": 3626,
          "sha512": "9d61d877e6915037ec99a454bd9a03217b94c677f0954c98105c711a6ad9855c1ef41303f332b14dc22af30e0f5a839630dbf2b6b386f66aab5c4913ae24fafd",
          "sha256": "2071b17f6d792fafadbad4b4f751ed40c13ebd37f6834a7a94308746cba7b453",
          "sha1": "7d434e1d3ec8b0e1838321bc7954628c5d6f0677",
          "md5": "186ba7c2ee70500e0e848017ec51b678"
        }
      ]
    }
  ]
}
