// DO NOT EDIT THIS FILE MANUALLY! IT IS AUTOGENERATED!

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    includeBuild("../build-logic")
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name = "mirrg.kotlin.helium-kotlin-2-2"
