{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-9/4.0.1/mirrg.kotlin.helium-kotlin-1-9-4.0.1.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-9",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.0.1.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.0.1.jar",
          "size": 20176,
          "sha512": "f6fd2ca5eec9d616298cdec0080f851aa33a8d804d8be8dfa4812b04187468a4fb3fc51c92cd8aab44579dffdaf4173c5c017f512d67b8c74f1ba73ad73fc02e",
          "sha256": "ffcda5bb0bc8bbc61ee9cd81fd817b903c3ddfc788b1dfb742b8fcf1267e6048",
          "sha1": "62acd2b11e7ac61aee5a226c4de19b83f37b4ac3",
          "md5": "e779581f53d80074d56bb2193d11f253"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.0.1.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.0.1.jar",
          "size": 20176,
          "sha512": "f6fd2ca5eec9d616298cdec0080f851aa33a8d804d8be8dfa4812b04187468a4fb3fc51c92cd8aab44579dffdaf4173c5c017f512d67b8c74f1ba73ad73fc02e",
          "sha256": "ffcda5bb0bc8bbc61ee9cd81fd817b903c3ddfc788b1dfb742b8fcf1267e6048",
          "sha1": "62acd2b11e7ac61aee5a226c4de19b83f37b4ac3",
          "md5": "e779581f53d80074d56bb2193d11f253"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.0.1-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.0.1-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    }
  ]
}
