{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-1/4.1.0/mirrg.kotlin.helium-kotlin-2-1-4.1.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-1",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.1.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.1.0.jar",
          "size": 18194,
          "sha512": "524390ea2bfaff867ef560ef3b8b01ca3524147d3fe4b762b1e596541711b8a62e3969bb01b1b798fd740f771d96b4710157a5d4f20c4edf58e2275b3136459a",
          "sha256": "02d05f9e32a6dd74c14224ae88ba0cf90d2f1c0fcb7281fa13016e1532ba3dcf",
          "sha1": "fd3e498601fca0cd627b70558e154499796e85ae",
          "md5": "5721d7768929c842686da5b0d6be73cb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.1.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.1.0.jar",
          "size": 18194,
          "sha512": "524390ea2bfaff867ef560ef3b8b01ca3524147d3fe4b762b1e596541711b8a62e3969bb01b1b798fd740f771d96b4710157a5d4f20c4edf58e2275b3136459a",
          "sha256": "02d05f9e32a6dd74c14224ae88ba0cf90d2f1c0fcb7281fa13016e1532ba3dcf",
          "sha1": "fd3e498601fca0cd627b70558e154499796e85ae",
          "md5": "5721d7768929c842686da5b0d6be73cb"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.1.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.1.0-sources.jar",
          "size": 3626,
          "sha512": "9d61d877e6915037ec99a454bd9a03217b94c677f0954c98105c711a6ad9855c1ef41303f332b14dc22af30e0f5a839630dbf2b6b386f66aab5c4913ae24fafd",
          "sha256": "2071b17f6d792fafadbad4b4f751ed40c13ebd37f6834a7a94308746cba7b453",
          "sha1": "7d434e1d3ec8b0e1838321bc7954628c5d6f0677",
          "md5": "186ba7c2ee70500e0e848017ec51b678"
        }
      ]
    }
  ]
}
