{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-1/4.4.0/mirrg.kotlin.helium-kotlin-2-1-4.4.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-1",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.4.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.4.0.jar",
          "size": 19173,
          "sha512": "b75f26f2a10afe51a543bb1313eca232da3aa37c6ea17ec9312dead1c476925a6db84419395c55d684a4b50ceb5fe26cc7aab73fce724f411215a42f05909832",
          "sha256": "aac5587fc8e083ad0c8bf47f9f2c7b5dc20438a8802c8061b279b91273f2e4dc",
          "sha1": "5d0e71fcbd475a769d87f7f6ab3d505b26e60145",
          "md5": "a2ffe20ac33cb742946ca050a8bba1bf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.4.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.4.0.jar",
          "size": 19173,
          "sha512": "b75f26f2a10afe51a543bb1313eca232da3aa37c6ea17ec9312dead1c476925a6db84419395c55d684a4b50ceb5fe26cc7aab73fce724f411215a42f05909832",
          "sha256": "aac5587fc8e083ad0c8bf47f9f2c7b5dc20438a8802c8061b279b91273f2e4dc",
          "sha1": "5d0e71fcbd475a769d87f7f6ab3d505b26e60145",
          "md5": "a2ffe20ac33cb742946ca050a8bba1bf"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.4.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.4.0-sources.jar",
          "size": 4028,
          "sha512": "5ef4b0c357557f9dbd9b211aeb51bc8ee7c816125ccb0f977761f621ea10c6e0f9b11a37ed28036a916f582c550f8136405c1c51d6eeadc15f367df9398b8dfd",
          "sha256": "dfe319ee38219a70fd6a327c62442fa5c9f7300902beacfcd24ac86783d7ee8a",
          "sha1": "4c1e2fcd3897c74d99fbe3411ba98bf3744d189a",
          "md5": "f9cf3bbfc427f9ab74b6359e49c7133d"
        }
      ]
    }
  ]
}
