{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-2/4.3.0/mirrg.kotlin.helium-kotlin-2-2-4.3.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-2",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.3.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.3.0.jar",
          "size": 18733,
          "sha512": "81be5303efa2c25aa9e738b1978ee0433eb7692babf25271c4202295f0c7e160c6206f55bed3af5783b4156d5cacddb1988fffaa3868c3cdbd35aa646ecebb32",
          "sha256": "6bb7d8a8550f2c79e84e82b77e01147c2e3b6a0b9ddeffc08711740f92d3ddb3",
          "sha1": "ce4ac4d3b1e80651ad4ae86d0635009549ec119c",
          "md5": "157f48ead2c35521d8e422ddcb914e62"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.3.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.3.0.jar",
          "size": 18733,
          "sha512": "81be5303efa2c25aa9e738b1978ee0433eb7692babf25271c4202295f0c7e160c6206f55bed3af5783b4156d5cacddb1988fffaa3868c3cdbd35aa646ecebb32",
          "sha256": "6bb7d8a8550f2c79e84e82b77e01147c2e3b6a0b9ddeffc08711740f92d3ddb3",
          "sha1": "ce4ac4d3b1e80651ad4ae86d0635009549ec119c",
          "md5": "157f48ead2c35521d8e422ddcb914e62"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.3.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.3.0-sources.jar",
          "size": 3797,
          "sha512": "10b2749af16fe3e272cc741a193ab9d8c8b635c44c4c4ddd483ba3a737544ff39ec390e5f3d2b3e99d397e74fd7770183a49dde6c277651d9bbfdc672c95e2e5",
          "sha256": "f774c0348ba67ca581353115b1eea93207dd3c1dc88a78548caf7ce81a7780e3",
          "sha1": "c1e847f8c4faf3dfb9da97744313ee5a27cdfb21",
          "md5": "73401ad3093fe01879126c8e622408d9"
        }
      ]
    }
  ]
}
