{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-9/4.3.0/mirrg.kotlin.helium-kotlin-1-9-4.3.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-9",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.3.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.3.0.jar",
          "size": 21007,
          "sha512": "c37d85801ac6864f1ff67d28819bb5145d2035a69286c6e9671a666d11ec4dca16bc9a30f817e82a9e8346eed04f00306b33d659087ee9596cb1a4d0eda0d123",
          "sha256": "f0cabcb3d6a2d03042aae1483998c9bfc048c0b7abc609999ba6fdd2c5d45036",
          "sha1": "560a6ab262b48b1a79ca45ec313034dde45ad0d8",
          "md5": "9ccf66b9b9f9bc1c8db527ba4cdc8356"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.3.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.3.0.jar",
          "size": 21007,
          "sha512": "c37d85801ac6864f1ff67d28819bb5145d2035a69286c6e9671a666d11ec4dca16bc9a30f817e82a9e8346eed04f00306b33d659087ee9596cb1a4d0eda0d123",
          "sha256": "f0cabcb3d6a2d03042aae1483998c9bfc048c0b7abc609999ba6fdd2c5d45036",
          "sha1": "560a6ab262b48b1a79ca45ec313034dde45ad0d8",
          "md5": "9ccf66b9b9f9bc1c8db527ba4cdc8356"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.3.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.3.0-sources.jar",
          "size": 3797,
          "sha512": "10b2749af16fe3e272cc741a193ab9d8c8b635c44c4c4ddd483ba3a737544ff39ec390e5f3d2b3e99d397e74fd7770183a49dde6c277651d9bbfdc672c95e2e5",
          "sha256": "f774c0348ba67ca581353115b1eea93207dd3c1dc88a78548caf7ce81a7780e3",
          "sha1": "c1e847f8c4faf3dfb9da97744313ee5a27cdfb21",
          "md5": "73401ad3093fe01879126c8e622408d9"
        }
      ]
    }
  ]
}
