{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium/1.0.0/mirrg.kotlin.helium-1.0.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-js-1.0.0.klib",
          "url": "mirrg.kotlin.helium-js-1.0.0.klib",
          "size": 22335,
          "sha512": "28b1af7a5abec4dc83f2cf0486abdc7a5ebfb38ac6c3800f755677cd8a00c70c5ba93791f1928f4e7d6767496732e312155fb00366d9b9efa194d8574d5646fe",
          "sha256": "f596e4d6172e2e2434c4cde4bcced1d14dcb1293386cf8dc404eec0e65cb8a20",
          "sha1": "080fbd143221d0f67f8e3bb35ca1761f572b14b4",
          "md5": "90edae81c306e7eb87b4d1f0b75fa7b1"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-js-1.0.0.klib",
          "url": "mirrg.kotlin.helium-js-1.0.0.klib",
          "size": 22335,
          "sha512": "28b1af7a5abec4dc83f2cf0486abdc7a5ebfb38ac6c3800f755677cd8a00c70c5ba93791f1928f4e7d6767496732e312155fb00366d9b9efa194d8574d5646fe",
          "sha256": "f596e4d6172e2e2434c4cde4bcced1d14dcb1293386cf8dc404eec0e65cb8a20",
          "sha1": "080fbd143221d0f67f8e3bb35ca1761f572b14b4",
          "md5": "90edae81c306e7eb87b4d1f0b75fa7b1"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-js-1.0.0-sources.jar",
          "url": "mirrg.kotlin.helium-js-1.0.0-sources.jar",
          "size": 3516,
          "sha512": "16f328c14e4c8d51e306d7be326a5bba000edf7be1c816c6a5040da8529c6f84cfd094e377e1e3b359ceab1c258255041cce09b6089e22ae1b6d7753da6784ea",
          "sha256": "0e1a7c77d0cb1563166c7482ffea926d9edaaafe43e32e9c4f13316ffddb1df1",
          "sha1": "5bf059bff47c27d5e2b664021017ca3fd9d71584",
          "md5": "b3a1ad12d5f11c4277f36077942dc05d"
        }
      ]
    }
  ]
}
