{
  "formatVersion": "1.1",
  "component": {
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-0",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-metadata-4.0.1.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-4.0.1.jar",
          "size": 8653,
          "sha512": "eb571568e8b10100ad867d94b2f340749c1e564b8d54ad06bcbcfed8f092f9e0fb47aeeb9a09d31e5d118435ba84fa47abc5b9df560dbee1adc8e52e79cee9d7",
          "sha256": "e2e020a0e2f644bdbcac218b76764a0ad87487e374b3f9b9afbb830cfa780b74",
          "sha1": "50b00bb358128cd24128279d60bd796cf12f2b31",
          "md5": "7713c05aa05a50641902d11cb834d5be"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-kotlin-4.0.1-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-4.0.1-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-0-js/4.0.1/mirrg.kotlin.helium-kotlin-2-0-js-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-0-js",
        "version": "4.0.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-0-js/4.0.1/mirrg.kotlin.helium-kotlin-2-0-js-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-0-js",
        "version": "4.0.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-0-js/4.0.1/mirrg.kotlin.helium-kotlin-2-0-js-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-0-js",
        "version": "4.0.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-0-jvm/4.0.1/mirrg.kotlin.helium-kotlin-2-0-jvm-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-0-jvm",
        "version": "4.0.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-0-jvm/4.0.1/mirrg.kotlin.helium-kotlin-2-0-jvm-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-0-jvm",
        "version": "4.0.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-0-jvm/4.0.1/mirrg.kotlin.helium-kotlin-2-0-jvm-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-0-jvm",
        "version": "4.0.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-0-linuxarm64/4.0.1/mirrg.kotlin.helium-kotlin-2-0-linuxarm64-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-0-linuxarm64",
        "version": "4.0.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-0-linuxarm64/4.0.1/mirrg.kotlin.helium-kotlin-2-0-linuxarm64-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-0-linuxarm64",
        "version": "4.0.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-0-linuxx64/4.0.1/mirrg.kotlin.helium-kotlin-2-0-linuxx64-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-0-linuxx64",
        "version": "4.0.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-0-linuxx64/4.0.1/mirrg.kotlin.helium-kotlin-2-0-linuxx64-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-0-linuxx64",
        "version": "4.0.1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-0-mingwx64/4.0.1/mirrg.kotlin.helium-kotlin-2-0-mingwx64-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-0-mingwx64",
        "version": "4.0.1"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-0-mingwx64/4.0.1/mirrg.kotlin.helium-kotlin-2-0-mingwx64-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-0-mingwx64",
        "version": "4.0.1"
      }
    }
  ]
}
