{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-1/4.4.0/mirrg.kotlin.helium-kotlin-2-1-4.4.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-1",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-js-4.4.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-1-js-4.4.0.klib",
          "size": 29411,
          "sha512": "ae19477221c2caee25e4e81d772e0bd6b0ffeef3549308b35dd82f050c074d5f9491d1535ad16057f9bb2d411519f84360d1fac555a25c83bb6ed9dec0e31538",
          "sha256": "fb4cb045b89c79bd59cd3d66dd5a540c3fb1a19cb15e92fdcba6e620aede7a2b",
          "sha1": "733fb4772f6f1b171a66ca48f87e2befa023d7b7",
          "md5": "84bff807569f0f93368c9f23ae08c5d5"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-js-4.4.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-1-js-4.4.0.klib",
          "size": 29411,
          "sha512": "ae19477221c2caee25e4e81d772e0bd6b0ffeef3549308b35dd82f050c074d5f9491d1535ad16057f9bb2d411519f84360d1fac555a25c83bb6ed9dec0e31538",
          "sha256": "fb4cb045b89c79bd59cd3d66dd5a540c3fb1a19cb15e92fdcba6e620aede7a2b",
          "sha1": "733fb4772f6f1b171a66ca48f87e2befa023d7b7",
          "md5": "84bff807569f0f93368c9f23ae08c5d5"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-js-4.4.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-js-4.4.0-sources.jar",
          "size": 4028,
          "sha512": "5ef4b0c357557f9dbd9b211aeb51bc8ee7c816125ccb0f977761f621ea10c6e0f9b11a37ed28036a916f582c550f8136405c1c51d6eeadc15f367df9398b8dfd",
          "sha256": "dfe319ee38219a70fd6a327c62442fa5c9f7300902beacfcd24ac86783d7ee8a",
          "sha1": "4c1e2fcd3897c74d99fbe3411ba98bf3744d189a",
          "md5": "f9cf3bbfc427f9ab74b6359e49c7133d"
        }
      ]
    }
  ]
}
