{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-8/4.4.0/mirrg.kotlin.helium-kotlin-1-8-4.4.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-8",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-8-linuxarm64-4.4.0.klib",
          "size": 25393,
          "sha512": "dfc1f7aa31dc0b168febd57f8f7756b2ffe1bdf5f357e46476940d914f0ab9d0630b0a7460d19a9b1a7f26990ccc391d14fc772e288de631114972851538f480",
          "sha256": "b48d88a108361672360c2eec9ba7acab6c37454d601ad9cd86507bf22af7a78e",
          "sha1": "10cf62fcd4acc3bf6cb98da95ae5042a5553bac5",
          "md5": "3e0d03ad0cafcd8e915ed61b2ab17451"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8-linuxarm64-4.4.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-8-linuxarm64-4.4.0-sources.jar",
          "size": 4028,
          "sha512": "5ef4b0c357557f9dbd9b211aeb51bc8ee7c816125ccb0f977761f621ea10c6e0f9b11a37ed28036a916f582c550f8136405c1c51d6eeadc15f367df9398b8dfd",
          "sha256": "dfe319ee38219a70fd6a327c62442fa5c9f7300902beacfcd24ac86783d7ee8a",
          "sha1": "4c1e2fcd3897c74d99fbe3411ba98bf3744d189a",
          "md5": "f9cf3bbfc427f9ab74b6359e49c7133d"
        }
      ]
    }
  ]
}
