{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium/1.1.0/mirrg.kotlin.helium-1.1.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium.klib",
          "url": "mirrg.kotlin.helium-mingwx64-1.1.0.klib",
          "size": 23966,
          "sha512": "10fcea029a60c5151c178b047dab956f462d999aad241b4e7214343649a274d110d734e7491b8d2dc5353e782db64fef401317f161016eb8b691d0f32f0558de",
          "sha256": "1b12c5c36882f42f563cb7dc1ba7ed1744e2f7de555832071a1a3afaeb748e37",
          "sha1": "892f7a38c007dacdb173e109c3ff29c11e0ad6c8",
          "md5": "97b5ca62689ef58cb18eeec42d1c3ad1"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-mingwx64-1.1.0-sources.jar",
          "url": "mirrg.kotlin.helium-mingwx64-1.1.0-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    }
  ]
}
