{
  "formatVersion": "1.1",
  "component": {
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-1",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-metadata-4.1.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-4.1.0.jar",
          "size": 8736,
          "sha512": "00543f9fcf1f6485bd7dc24e9fe6899f85bcf4dc24bd110c690bc2e7d8a57e8786ce847b1f6bdee26ed8d62499297b7bf7f4ef1175aa2896587d950bb578fdba",
          "sha256": "2cc828ab943a98154d0ab0080e13aa00dc1c41d35e4abbce3c510b4bf9ae3fd6",
          "sha1": "36bae98a97043febcb034db111d24a0fa302951a",
          "md5": "677548703af4ce019a27dfcbdecb6a37"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-kotlin-4.1.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-4.1.0-sources.jar",
          "size": 3626,
          "sha512": "9d61d877e6915037ec99a454bd9a03217b94c677f0954c98105c711a6ad9855c1ef41303f332b14dc22af30e0f5a839630dbf2b6b386f66aab5c4913ae24fafd",
          "sha256": "2071b17f6d792fafadbad4b4f751ed40c13ebd37f6834a7a94308746cba7b453",
          "sha1": "7d434e1d3ec8b0e1838321bc7954628c5d6f0677",
          "md5": "186ba7c2ee70500e0e848017ec51b678"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-js/4.1.0/mirrg.kotlin.helium-kotlin-2-1-js-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-js",
        "version": "4.1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-js/4.1.0/mirrg.kotlin.helium-kotlin-2-1-js-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-js",
        "version": "4.1.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-js/4.1.0/mirrg.kotlin.helium-kotlin-2-1-js-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-js",
        "version": "4.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-jvm/4.1.0/mirrg.kotlin.helium-kotlin-2-1-jvm-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-jvm",
        "version": "4.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-jvm/4.1.0/mirrg.kotlin.helium-kotlin-2-1-jvm-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-jvm",
        "version": "4.1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-jvm/4.1.0/mirrg.kotlin.helium-kotlin-2-1-jvm-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-jvm",
        "version": "4.1.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxarm64/4.1.0/mirrg.kotlin.helium-kotlin-2-1-linuxarm64-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxarm64",
        "version": "4.1.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxarm64/4.1.0/mirrg.kotlin.helium-kotlin-2-1-linuxarm64-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxarm64",
        "version": "4.1.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxx64/4.1.0/mirrg.kotlin.helium-kotlin-2-1-linuxx64-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxx64",
        "version": "4.1.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxx64/4.1.0/mirrg.kotlin.helium-kotlin-2-1-linuxx64-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxx64",
        "version": "4.1.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-mingwx64/4.1.0/mirrg.kotlin.helium-kotlin-2-1-mingwx64-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-mingwx64",
        "version": "4.1.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-mingwx64/4.1.0/mirrg.kotlin.helium-kotlin-2-1-mingwx64-4.1.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-mingwx64",
        "version": "4.1.0"
      }
    }
  ]
}
