{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium/1.0.0/mirrg.kotlin.helium-1.0.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium.klib",
          "url": "mirrg.kotlin.helium-linuxx64-1.0.0.klib",
          "size": 23818,
          "sha512": "f465f9487a7ad4cb9439ba1784ff2147271678c99ffbd4d7d1206af2e3b57d8553091d3d02dc68b643b52bfeaece4f2a8744dcd71044840084593df400084f22",
          "sha256": "87fdcff0d6fa06e1bc6ec9093ed57eb14fc3e37631b16780a8c1b81f019a5bd7",
          "sha1": "cfa084815a9dc05a71229f31f175dcdb31216996",
          "md5": "39418c301ddb8205ba45358870a67e51"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-linuxx64-1.0.0-sources.jar",
          "url": "mirrg.kotlin.helium-linuxx64-1.0.0-sources.jar",
          "size": 3516,
          "sha512": "16f328c14e4c8d51e306d7be326a5bba000edf7be1c816c6a5040da8529c6f84cfd094e377e1e3b359ceab1c258255041cce09b6089e22ae1b6d7753da6784ea",
          "sha256": "0e1a7c77d0cb1563166c7482ffea926d9edaaafe43e32e9c4f13316ffddb1df1",
          "sha1": "5bf059bff47c27d5e2b664021017ca3fd9d71584",
          "md5": "b3a1ad12d5f11c4277f36077942dc05d"
        }
      ]
    }
  ]
}
