{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-1/4.0.1/mirrg.kotlin.helium-kotlin-2-1-4.0.1.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-1",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.0.1.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.0.1.jar",
          "size": 17926,
          "sha512": "8232214f9816cdb041af279c29572b7e21906bef2620ed452260bf9d03c9315a680b765818767d07808e55f310adaeb371a860f20f31e9d9906fbd6c9c16674f",
          "sha256": "e943c47ebb8f3abd4fea99756b05cb27e3bac941b561f7b1105fe78b179bae09",
          "sha1": "1af9c1599bda17a3907d2c4336f4596fb53452c6",
          "md5": "fbe56e13894fe0d9dfffd15c74e9759b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.0.1.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.0.1.jar",
          "size": 17926,
          "sha512": "8232214f9816cdb041af279c29572b7e21906bef2620ed452260bf9d03c9315a680b765818767d07808e55f310adaeb371a860f20f31e9d9906fbd6c9c16674f",
          "sha256": "e943c47ebb8f3abd4fea99756b05cb27e3bac941b561f7b1105fe78b179bae09",
          "sha1": "1af9c1599bda17a3907d2c4336f4596fb53452c6",
          "md5": "fbe56e13894fe0d9dfffd15c74e9759b"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.0.1-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-jvm-4.0.1-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    }
  ]
}
