{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-0/4.0.1/mirrg.kotlin.helium-kotlin-2-0-4.0.1.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-0",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-js-4.0.1.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-0-js-4.0.1.klib",
          "size": 25907,
          "sha512": "826d1501ba37e36f2f991bd980a0a98e5512cf6ecb0a1da217f01c71063f5f7f3bf321c49bc88d965546c029c55321e527b035d7b9232ee91385c873950e9efa",
          "sha256": "210766cf4d0c15539e873a5b4fc457d8ed776f48adf4724af10469a2ecc36042",
          "sha1": "1e31f5cc2aae84b8beec102ff2f3698b54cb21a0",
          "md5": "0132004ba618d8a0613962a0e892c653"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-js-4.0.1.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-0-js-4.0.1.klib",
          "size": 25907,
          "sha512": "826d1501ba37e36f2f991bd980a0a98e5512cf6ecb0a1da217f01c71063f5f7f3bf321c49bc88d965546c029c55321e527b035d7b9232ee91385c873950e9efa",
          "sha256": "210766cf4d0c15539e873a5b4fc457d8ed776f48adf4724af10469a2ecc36042",
          "sha1": "1e31f5cc2aae84b8beec102ff2f3698b54cb21a0",
          "md5": "0132004ba618d8a0613962a0e892c653"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-js-4.0.1-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-js-4.0.1-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    }
  ]
}
