{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-7/4.3.0/mirrg.kotlin.helium-kotlin-1-7-4.3.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-7",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-7.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-7-linuxx64-4.3.0.klib",
          "size": 24238,
          "sha512": "973bf891d04bc784c1a2186bc2bd8c27421616f3f6360c225375cb63283e8a5b3eedcb74e60a743fab8462b3035c9535d404d9ce3b559ca2c5a098a5143ce833",
          "sha256": "cb75a06225984e70e3daa7597b998a4c35a0aad8cff711ccdf45ca408d26fcfc",
          "sha1": "7d3a6cb61e08e4e163fca162bd951ed8b300d31c",
          "md5": "9e634f0e3281fe81adf53bfebea2b115"
        }
      ]
    }
  ]
}
