{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-2/4.0.1/mirrg.kotlin.helium-kotlin-2-2-4.0.1.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-2",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-linuxX64Main-4.0.1.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-2-linuxx64-4.0.1.klib",
          "size": 22333,
          "sha512": "4d1cb0628ebb1e0ccaba016c059f1c4d5cb303366ce184e116e46118954ff2337757e4a8073509ebdb5c9f4b2cff80d6632c1d579419a21e2fb3950aba9df626",
          "sha256": "ab8e2379e89ccd9ce2186a766d92565ee6f7668cc72abf432bad92d83c6d9762",
          "sha1": "7969f1a9afa92a85fb72cbd5440f80d879c558de",
          "md5": "c5d48e4bb855c8f496ebd1e9d7f465f0"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-linuxx64-4.0.1-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-linuxx64-4.0.1-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    }
  ]
}
