{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-7/4.4.0/mirrg.kotlin.helium-kotlin-1-7-4.4.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-7",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-7-js-4.4.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-7-js-4.4.0.klib",
          "size": 27728,
          "sha512": "abeddbab82f9d622d6e4e052932d3a41379e139156bc0c14a3f70ac6bc1356feed12e56e30e7e89f1d4941c2486408f5f88effd40b3db3ab1f7c2de3b26be853",
          "sha256": "693aab693645cb4e15210f3057bc3b2e6cb5f2904b8b14b020c40571d4e6428e",
          "sha1": "38890a5334c8f9035bb71c6e1f71fc8270624dd6",
          "md5": "5e594f6025354c5568923779a47aafb4"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-7-js-4.4.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-7-js-4.4.0.klib",
          "size": 27728,
          "sha512": "abeddbab82f9d622d6e4e052932d3a41379e139156bc0c14a3f70ac6bc1356feed12e56e30e7e89f1d4941c2486408f5f88effd40b3db3ab1f7c2de3b26be853",
          "sha256": "693aab693645cb4e15210f3057bc3b2e6cb5f2904b8b14b020c40571d4e6428e",
          "sha1": "38890a5334c8f9035bb71c6e1f71fc8270624dd6",
          "md5": "5e594f6025354c5568923779a47aafb4"
        }
      ]
    }
  ]
}
