{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-9/4.4.0/mirrg.kotlin.helium-kotlin-1-9-4.4.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-9",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-js-4.4.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-9-js-4.4.0.klib",
          "size": 30068,
          "sha512": "d7369fe7510feb6898e6296636652a7de87a3e8e59c7071fd320111bca52dfe6f0093608deb065d3bb5fe9bfcbd7920e99673f81b8ce692ecc858449b4a111aa",
          "sha256": "789385e0b914d1a46a42d71115b9aa1c95824ef0fcd3299fd81543480b315a87",
          "sha1": "e6b72687caf6a1a2fe66d139415a439f9e98616c",
          "md5": "8f9e513275c4044fccff6e44293cbe5a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-js-4.4.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-9-js-4.4.0.klib",
          "size": 30068,
          "sha512": "d7369fe7510feb6898e6296636652a7de87a3e8e59c7071fd320111bca52dfe6f0093608deb065d3bb5fe9bfcbd7920e99673f81b8ce692ecc858449b4a111aa",
          "sha256": "789385e0b914d1a46a42d71115b9aa1c95824ef0fcd3299fd81543480b315a87",
          "sha1": "e6b72687caf6a1a2fe66d139415a439f9e98616c",
          "md5": "8f9e513275c4044fccff6e44293cbe5a"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-js-4.4.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-js-4.4.0-sources.jar",
          "size": 4028,
          "sha512": "5ef4b0c357557f9dbd9b211aeb51bc8ee7c816125ccb0f977761f621ea10c6e0f9b11a37ed28036a916f582c550f8136405c1c51d6eeadc15f367df9398b8dfd",
          "sha256": "dfe319ee38219a70fd6a327c62442fa5c9f7300902beacfcd24ac86783d7ee8a",
          "sha1": "4c1e2fcd3897c74d99fbe3411ba98bf3744d189a",
          "md5": "f9cf3bbfc427f9ab74b6359e49c7133d"
        }
      ]
    }
  ]
}
