{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-2/4.2.0/mirrg.kotlin.helium-kotlin-2-2-4.2.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-2",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.2.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.2.0.jar",
          "size": 18368,
          "sha512": "4e05f35a8ab71733dd597a25e93092fc5d1fe0779cf50d451ee10b42776b413aae14f81725c56bd5fd43f1ba7939b222c103358104653d3ea94227f4976f8cb4",
          "sha256": "7c0924f9568bdfbd5085c513cadc9c7f75cd7b65eb9b95481700cce35d217f9c",
          "sha1": "ef3c5140e939fe7b409dfdbcbe58ff56ccbd5985",
          "md5": "f9c8d7adc308bc6bbc50f94878e95daf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.2.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.2.0.jar",
          "size": 18368,
          "sha512": "4e05f35a8ab71733dd597a25e93092fc5d1fe0779cf50d451ee10b42776b413aae14f81725c56bd5fd43f1ba7939b222c103358104653d3ea94227f4976f8cb4",
          "sha256": "7c0924f9568bdfbd5085c513cadc9c7f75cd7b65eb9b95481700cce35d217f9c",
          "sha1": "ef3c5140e939fe7b409dfdbcbe58ff56ccbd5985",
          "md5": "f9c8d7adc308bc6bbc50f94878e95daf"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.2.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-jvm-4.2.0-sources.jar",
          "size": 3668,
          "sha512": "88e69b0a944fe896966342f4108ed2effa9da1b5deab08ba414424fcd1cd64e81a5ac3ef5b509c8a451141dbba19abefcaa8256205b62336fb6c341b42573ea2",
          "sha256": "2e82a2c8712db07e240ef87e1102ac3eaf7d9091d72119be618ec1204fbc8d90",
          "sha1": "a85c6845aed7e8355126fedebfd007e6a91dafca",
          "md5": "4893911cd7d818cc631dbbd20993c8e4"
        }
      ]
    }
  ]
}
