{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium/2.0.0/mirrg.kotlin.helium-2.0.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-js-2.0.0.klib",
          "url": "mirrg.kotlin.helium-js-2.0.0.klib",
          "size": 25887,
          "sha512": "ee807246048671f09b6b81cdd16b49bca6188109b891f5626c54080932fd16da2b39dc81e161231fc152b747e0cbb86f5bd692f40e03380f00f1fc3a33687a48",
          "sha256": "4be413bd9e0a4403438169b10be9ad3d981a3a7a8cb0f7e67d32615268de50ff",
          "sha1": "605ea4cff8ebb7a48167a907310b45a9d6ded78b",
          "md5": "4fe8429d042a66cf29fe46601a14d369"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-js-2.0.0.klib",
          "url": "mirrg.kotlin.helium-js-2.0.0.klib",
          "size": 25887,
          "sha512": "ee807246048671f09b6b81cdd16b49bca6188109b891f5626c54080932fd16da2b39dc81e161231fc152b747e0cbb86f5bd692f40e03380f00f1fc3a33687a48",
          "sha256": "4be413bd9e0a4403438169b10be9ad3d981a3a7a8cb0f7e67d32615268de50ff",
          "sha1": "605ea4cff8ebb7a48167a907310b45a9d6ded78b",
          "md5": "4fe8429d042a66cf29fe46601a14d369"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-js-2.0.0-sources.jar",
          "url": "mirrg.kotlin.helium-js-2.0.0-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    }
  ]
}
