{
  "formatVersion": "1.1",
  "component": {
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-1",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-metadata-4.4.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-4.4.0.jar",
          "size": 8991,
          "sha512": "402a1b156907c61198b22d4c7b7ccd6757dc9ef5d3ec671af0fc01b487b5f327a5bbe0753e879a8280b6998ae151c4dafd9d35c00c8609ec4e5c096638aa93ee",
          "sha256": "2067773eb3f88d65b136b4745aba56e84bc2756c5f6470e99df01a4d6120e8d5",
          "sha1": "a3f8cde00c4382e3e871b114c5588947768c3714",
          "md5": "b653d9fabc2ffd9f1ddfaf9d88aa04a0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-kotlin-4.4.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-4.4.0-sources.jar",
          "size": 4028,
          "sha512": "5ef4b0c357557f9dbd9b211aeb51bc8ee7c816125ccb0f977761f621ea10c6e0f9b11a37ed28036a916f582c550f8136405c1c51d6eeadc15f367df9398b8dfd",
          "sha256": "dfe319ee38219a70fd6a327c62442fa5c9f7300902beacfcd24ac86783d7ee8a",
          "sha1": "4c1e2fcd3897c74d99fbe3411ba98bf3744d189a",
          "md5": "f9cf3bbfc427f9ab74b6359e49c7133d"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-js/4.4.0/mirrg.kotlin.helium-kotlin-2-1-js-4.4.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-js",
        "version": "4.4.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-js/4.4.0/mirrg.kotlin.helium-kotlin-2-1-js-4.4.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-js",
        "version": "4.4.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-js/4.4.0/mirrg.kotlin.helium-kotlin-2-1-js-4.4.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-js",
        "version": "4.4.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-jvm/4.4.0/mirrg.kotlin.helium-kotlin-2-1-jvm-4.4.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-jvm",
        "version": "4.4.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-jvm/4.4.0/mirrg.kotlin.helium-kotlin-2-1-jvm-4.4.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-jvm",
        "version": "4.4.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-jvm/4.4.0/mirrg.kotlin.helium-kotlin-2-1-jvm-4.4.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-jvm",
        "version": "4.4.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxarm64/4.4.0/mirrg.kotlin.helium-kotlin-2-1-linuxarm64-4.4.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxarm64",
        "version": "4.4.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxarm64/4.4.0/mirrg.kotlin.helium-kotlin-2-1-linuxarm64-4.4.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxarm64",
        "version": "4.4.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxx64/4.4.0/mirrg.kotlin.helium-kotlin-2-1-linuxx64-4.4.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxx64",
        "version": "4.4.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxx64/4.4.0/mirrg.kotlin.helium-kotlin-2-1-linuxx64-4.4.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxx64",
        "version": "4.4.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-mingwx64/4.4.0/mirrg.kotlin.helium-kotlin-2-1-mingwx64-4.4.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-mingwx64",
        "version": "4.4.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-mingwx64/4.4.0/mirrg.kotlin.helium-kotlin-2-1-mingwx64-4.4.0.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-mingwx64",
        "version": "4.4.0"
      }
    }
  ]
}
