{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-8/4.4.0/mirrg.kotlin.helium-kotlin-1-8-4.4.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-8",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8-js-4.4.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-8-js-4.4.0.klib",
          "size": 27940,
          "sha512": "d88e15aae19be2d9b727dd828546b27b63023991bdd9faed41b5298b779c2dd2a26e8d126b27f36a07f282b087192d5e814793714d8234a2b50c8cb789132601",
          "sha256": "527e841995177ad3e935cfa0943cd2f705b17ad2278f173c8450b5afd1e70dfc",
          "sha1": "628c9aa3c9ea564c2cc1ef5494a39fc6a0b44236",
          "md5": "119121a090622af19d2ef55b03d1f443"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8-js-4.4.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-8-js-4.4.0.klib",
          "size": 27940,
          "sha512": "d88e15aae19be2d9b727dd828546b27b63023991bdd9faed41b5298b779c2dd2a26e8d126b27f36a07f282b087192d5e814793714d8234a2b50c8cb789132601",
          "sha256": "527e841995177ad3e935cfa0943cd2f705b17ad2278f173c8450b5afd1e70dfc",
          "sha1": "628c9aa3c9ea564c2cc1ef5494a39fc6a0b44236",
          "md5": "119121a090622af19d2ef55b03d1f443"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-8-js-4.4.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-8-js-4.4.0-sources.jar",
          "size": 4028,
          "sha512": "5ef4b0c357557f9dbd9b211aeb51bc8ee7c816125ccb0f977761f621ea10c6e0f9b11a37ed28036a916f582c550f8136405c1c51d6eeadc15f367df9398b8dfd",
          "sha256": "dfe319ee38219a70fd6a327c62442fa5c9f7300902beacfcd24ac86783d7ee8a",
          "sha1": "4c1e2fcd3897c74d99fbe3411ba98bf3744d189a",
          "md5": "f9cf3bbfc427f9ab74b6359e49c7133d"
        }
      ]
    }
  ]
}
