{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium/3.0.0/mirrg.kotlin.helium-3.0.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-linuxX64Main-3.0.0.klib",
          "url": "mirrg.kotlin.helium-linuxx64-3.0.0.klib",
          "size": 22125,
          "sha512": "122d7c385513733b5a699ac961886cfe70add264ce17ee463a4b82933b97e918e268afb11465b78d819a2feebef4303f3a1321bfcb9aeb59b9479f505867730f",
          "sha256": "95a1a6e4b1db42f656704385af8dd678da25444eafd082af33948c3a03f2ce98",
          "sha1": "54b03ada2714f7ee604d3589c5ca000fad1ad76d",
          "md5": "74d1211bef37708ae99b8c9a8e55459f"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-linuxx64-3.0.0-sources.jar",
          "url": "mirrg.kotlin.helium-linuxx64-3.0.0-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    }
  ]
}
