{
  "formatVersion": "1.1",
  "component": {
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-1",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-metadata-4.0.1.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-4.0.1.jar",
          "size": 8652,
          "sha512": "6ce8a36616c4fe4b0cecf05c85dd6e7c0bf49f8ff3348fe33a18f48513b8c101f04b3622630237d86ce5a668df4f9c391ca5203e646184e89f5e6618d8eaab0d",
          "sha256": "b14a3ad9a6445bbb432c0099b9b86eecd5f3d6fffcc4236b5d1457612f512de7",
          "sha1": "d6fca1ad44698218b12292e1b4b2c03108bacae6",
          "md5": "3cbfef7087ae1a42bd158fab8bb1fedf"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-kotlin-4.0.1-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-4.0.1-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-js/4.0.1/mirrg.kotlin.helium-kotlin-2-1-js-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-js",
        "version": "4.0.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-js/4.0.1/mirrg.kotlin.helium-kotlin-2-1-js-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-js",
        "version": "4.0.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-js/4.0.1/mirrg.kotlin.helium-kotlin-2-1-js-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-js",
        "version": "4.0.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-jvm/4.0.1/mirrg.kotlin.helium-kotlin-2-1-jvm-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-jvm",
        "version": "4.0.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-jvm/4.0.1/mirrg.kotlin.helium-kotlin-2-1-jvm-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-jvm",
        "version": "4.0.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-jvm/4.0.1/mirrg.kotlin.helium-kotlin-2-1-jvm-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-jvm",
        "version": "4.0.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxarm64/4.0.1/mirrg.kotlin.helium-kotlin-2-1-linuxarm64-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxarm64",
        "version": "4.0.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxarm64/4.0.1/mirrg.kotlin.helium-kotlin-2-1-linuxarm64-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxarm64",
        "version": "4.0.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxx64/4.0.1/mirrg.kotlin.helium-kotlin-2-1-linuxx64-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxx64",
        "version": "4.0.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-linuxx64/4.0.1/mirrg.kotlin.helium-kotlin-2-1-linuxx64-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-linuxx64",
        "version": "4.0.1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-mingwx64/4.0.1/mirrg.kotlin.helium-kotlin-2-1-mingwx64-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-mingwx64",
        "version": "4.0.1"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mirrg.kotlin.helium-kotlin-2-1-mingwx64/4.0.1/mirrg.kotlin.helium-kotlin-2-1-mingwx64-4.0.1.module",
        "group": "mirrg.kotlin",
        "module": "mirrg.kotlin.helium-kotlin-2-1-mingwx64",
        "version": "4.0.1"
      }
    }
  ]
}
