{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-2/4.1.0/mirrg.kotlin.helium-kotlin-2-2-4.1.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-2",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-js-4.1.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-2-js-4.1.0.klib",
          "size": 26595,
          "sha512": "5254463685b6d23e5de129f15d163f16bd05ce38ad20cc4f9330ca73dcdd09d9afac631a2bc917d887b1e2f5906a5de2eff66e483720f8af570f8bd4e3416b09",
          "sha256": "ee037f5818d809f89fc95e12fac7b78e5ffb37b2337c68ba608967a6dc93ca9f",
          "sha1": "ceffbc2c5da30f460885793f865462bd6c476914",
          "md5": "9d25f1ffc702cb99b463303e84d571e8"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-js-4.1.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-2-js-4.1.0.klib",
          "size": 26595,
          "sha512": "5254463685b6d23e5de129f15d163f16bd05ce38ad20cc4f9330ca73dcdd09d9afac631a2bc917d887b1e2f5906a5de2eff66e483720f8af570f8bd4e3416b09",
          "sha256": "ee037f5818d809f89fc95e12fac7b78e5ffb37b2337c68ba608967a6dc93ca9f",
          "sha1": "ceffbc2c5da30f460885793f865462bd6c476914",
          "md5": "9d25f1ffc702cb99b463303e84d571e8"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-js-4.1.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-js-4.1.0-sources.jar",
          "size": 3626,
          "sha512": "9d61d877e6915037ec99a454bd9a03217b94c677f0954c98105c711a6ad9855c1ef41303f332b14dc22af30e0f5a839630dbf2b6b386f66aab5c4913ae24fafd",
          "sha256": "2071b17f6d792fafadbad4b4f751ed40c13ebd37f6834a7a94308746cba7b453",
          "sha1": "7d434e1d3ec8b0e1838321bc7954628c5d6f0677",
          "md5": "186ba7c2ee70500e0e848017ec51b678"
        }
      ]
    }
  ]
}
