{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-1/4.0.1/mirrg.kotlin.helium-kotlin-2-1-4.0.1.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-1",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-js-4.0.1.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-1-js-4.0.1.klib",
          "size": 25918,
          "sha512": "9d6de0a8c5a2987d0352594e24e9e7fab371a6ab0e54f7feaccd1042b20a5c6c3af5eff89233a65d1285ac4ffa8d5015ebaae4e196254c0c28a9ebb0a817e7a9",
          "sha256": "7f46da9dcfc28e359dac471d5298b55d87cccc2c05a203d28b64535f5cc8592e",
          "sha1": "0103a74608892691710cd133e0eaafc250fbe542",
          "md5": "b662020aba7b23aee75a177741b2c936"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-js-4.0.1.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-1-js-4.0.1.klib",
          "size": 25918,
          "sha512": "9d6de0a8c5a2987d0352594e24e9e7fab371a6ab0e54f7feaccd1042b20a5c6c3af5eff89233a65d1285ac4ffa8d5015ebaae4e196254c0c28a9ebb0a817e7a9",
          "sha256": "7f46da9dcfc28e359dac471d5298b55d87cccc2c05a203d28b64535f5cc8592e",
          "sha1": "0103a74608892691710cd133e0eaafc250fbe542",
          "md5": "b662020aba7b23aee75a177741b2c936"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-1-js-4.0.1-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-1-js-4.0.1-sources.jar",
          "size": 3545,
          "sha512": "61203412ce04aec3620a1af80c10e0f6c45501c44d9b217977d7d302990ac1af896ab243a462b292946df677b8a522978a64aba43f54adec065698e7966a05b9",
          "sha256": "6a3eb31e9e8280bafd04079ca5178392662994b43f69a399b928d58ffe1b76b1",
          "sha1": "cd7c3a41d7cd5609e35be1592a5812f7f5e5e2c4",
          "md5": "6fbae48f6618002250a0ae1e96d7bbc9"
        }
      ]
    }
  ]
}
