{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-9/4.4.0/mirrg.kotlin.helium-kotlin-1-9-4.4.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-9",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.4.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.4.0.jar",
          "size": 21382,
          "sha512": "907272ce79ae706c8b2f265f15917e258d675f593389dcde2930e0c836d09d329d73fb9e3d9d4395af5c1c823f6425178dbe271dd6ea8f77e1775a0b25a5a51b",
          "sha256": "c0c6b8e7b40766852c71b8211a50cb26c556cb35a226df4340160da7b395babe",
          "sha1": "6ad6485daed8f8b13effd2b06e34e09e1ed436c0",
          "md5": "65d7884ac02873b9c551dff121d28a42"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.4.0.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.4.0.jar",
          "size": 21382,
          "sha512": "907272ce79ae706c8b2f265f15917e258d675f593389dcde2930e0c836d09d329d73fb9e3d9d4395af5c1c823f6425178dbe271dd6ea8f77e1775a0b25a5a51b",
          "sha256": "c0c6b8e7b40766852c71b8211a50cb26c556cb35a226df4340160da7b395babe",
          "sha1": "6ad6485daed8f8b13effd2b06e34e09e1ed436c0",
          "md5": "65d7884ac02873b9c551dff121d28a42"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.4.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-1-9-jvm-4.4.0-sources.jar",
          "size": 4028,
          "sha512": "5ef4b0c357557f9dbd9b211aeb51bc8ee7c816125ccb0f977761f621ea10c6e0f9b11a37ed28036a916f582c550f8136405c1c51d6eeadc15f367df9398b8dfd",
          "sha256": "dfe319ee38219a70fd6a327c62442fa5c9f7300902beacfcd24ac86783d7ee8a",
          "sha1": "4c1e2fcd3897c74d99fbe3411ba98bf3744d189a",
          "md5": "f9cf3bbfc427f9ab74b6359e49c7133d"
        }
      ]
    }
  ]
}
