{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-2/4.1.0/mirrg.kotlin.helium-kotlin-2-2-4.1.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-2",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-linuxX64Main-4.1.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-2-linuxx64-4.1.0.klib",
          "size": 22864,
          "sha512": "0fdef66591c5f95c90fc9e733c4355a8384f0bc312b41c225fa5b72d27df648c030f62c6a19de06d2b60c835b7b88c3496af67059ed41e54c9e908f62a68e92a",
          "sha256": "2975461c6b3dbb9f74451c9516761cbae4b466d2101f4deb68ae3e9e68bc20c6",
          "sha1": "d2bff6616a91ba9d912328140c239fc272424970",
          "md5": "ec418e0a20fa0b8062b82a3e70d1a717"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-2-linuxx64-4.1.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-2-linuxx64-4.1.0-sources.jar",
          "size": 3626,
          "sha512": "9d61d877e6915037ec99a454bd9a03217b94c677f0954c98105c711a6ad9855c1ef41303f332b14dc22af30e0f5a839630dbf2b6b386f66aab5c4913ae24fafd",
          "sha256": "2071b17f6d792fafadbad4b4f751ed40c13ebd37f6834a7a94308746cba7b453",
          "sha1": "7d434e1d3ec8b0e1838321bc7954628c5d6f0677",
          "md5": "186ba7c2ee70500e0e848017ec51b678"
        }
      ]
    }
  ]
}
