{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-2-0/4.2.0/mirrg.kotlin.helium-kotlin-2-0-4.2.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-2-0",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-js-4.2.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-0-js-4.2.0.klib",
          "size": 26831,
          "sha512": "34447bfd3312bffb787261f573d8c6ddafc4335ba7d012ad3ba4b18c0010020c6e20f2d06ddab0e26d053f683b04663352211dcbd9fccd39e97ef1e4c147b1b2",
          "sha256": "478f19608559d8015052d4f5416aac5f3d9865e8a2afb135e22b3cdc99f8e3d4",
          "sha1": "0281a667d48c4839237418addefff21e3e4a7bae",
          "md5": "1c3cae9d95acac94366a1e925786b0d9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-js-4.2.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-2-0-js-4.2.0.klib",
          "size": 26831,
          "sha512": "34447bfd3312bffb787261f573d8c6ddafc4335ba7d012ad3ba4b18c0010020c6e20f2d06ddab0e26d053f683b04663352211dcbd9fccd39e97ef1e4c147b1b2",
          "sha256": "478f19608559d8015052d4f5416aac5f3d9865e8a2afb135e22b3cdc99f8e3d4",
          "sha1": "0281a667d48c4839237418addefff21e3e4a7bae",
          "md5": "1c3cae9d95acac94366a1e925786b0d9"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-2-0-js-4.2.0-sources.jar",
          "url": "mirrg.kotlin.helium-kotlin-2-0-js-4.2.0-sources.jar",
          "size": 3668,
          "sha512": "88e69b0a944fe896966342f4108ed2effa9da1b5deab08ba414424fcd1cd64e81a5ac3ef5b509c8a451141dbba19abefcaa8256205b62336fb6c341b42573ea2",
          "sha256": "2e82a2c8712db07e240ef87e1102ac3eaf7d9091d72119be618ec1204fbc8d90",
          "sha1": "a85c6845aed7e8355126fedebfd007e6a91dafca",
          "md5": "4893911cd7d818cc631dbbd20993c8e4"
        }
      ]
    }
  ]
}
