name: Build

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-java@v2

    - name: Build
      run: |
        bash gradlew build
