name: Build

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: adopt

    - uses: actions/checkout@v2

    - name: Build
      run: |
        bash gradlew build
