{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mirrg.kotlin.helium-kotlin-1-7/4.3.0/mirrg.kotlin.helium-kotlin-1-7-4.3.0.module",
    "group": "mirrg.kotlin",
    "module": "mirrg.kotlin.helium-kotlin-1-7",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-7-js-4.3.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-7-js-4.3.0.klib",
          "size": 26645,
          "sha512": "37b7c7351b4385cea89464bc7e871d6bc9a782b33a8e47d66accb9ecddeea7005315fe3122390c5bb61d1a16d492fbbb6966f2c23f6cf92fdbddd1b3a25dbcf2",
          "sha256": "7115869d21bd8b83d414fa7c2b25e528b15cba43187583ca696bdf4e72af3335",
          "sha1": "fc302243f6abcaf84ce0ddecda6e5c995e8425e7",
          "md5": "90df7d00aa4a85c5c7ba69def1bf308d"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "mirrg.kotlin.helium-kotlin-1-7-js-4.3.0.klib",
          "url": "mirrg.kotlin.helium-kotlin-1-7-js-4.3.0.klib",
          "size": 26645,
          "sha512": "37b7c7351b4385cea89464bc7e871d6bc9a782b33a8e47d66accb9ecddeea7005315fe3122390c5bb61d1a16d492fbbb6966f2c23f6cf92fdbddd1b3a25dbcf2",
          "sha256": "7115869d21bd8b83d414fa7c2b25e528b15cba43187583ca696bdf4e72af3335",
          "sha1": "fc302243f6abcaf84ce0ddecda6e5c995e8425e7",
          "md5": "90df7d00aa4a85c5c7ba69def1bf308d"
        }
      ]
    }
  ]
}
